<div style="padding-bottom:15px">
	<div align="center">
		<strong>Issue Out Report</strong> 
	</div>
	<br>
	<form>
		<label for="from_date">From Date</label>	
		<input type="date" id="from_date">
		
		<label for="to_date">To Date</label>
		<input type="date" id="to_date">
									
		<button id="go_button" class="btn btn-primary">Go</button>
	</form>
</div>

<iframe src="/report/issue-out" width="100%" height="100%">IFrame Not Supported!</iframe>

<link rel="stylesheet" type="text/css" href="/assets/css/reports.css">
<script type="text/javascript" src="/assets/js/reports.js"></script>
<script type="text/javascript">
    $('document').ready(function() {
        $('form').on('submit', function(e) {
            e.preventDefault();
            var from_date = ($('#from_date').val())?$('#from_date').val():false;
            var to_date = ($('#to_date').val())?$('#to_date').val():false;
            var get = $('iframe')[0].src.split('/?')[0]+'/?from_date='+from_date+'&to_date='+to_date;
			alert(get);
			if(from_date && to_date) {
                return $('iframe')[0].src=get;
            }
        });
    });
</script>