<div style="padding-bottom:15px">
	<div align="center">
		<strong>Monthly Report</strong> 
	</div>
	<br>
	
	<label for="from_month">From Date</label>	
	<input type="month" id="from_month">
	
	<label for="to_month">To Date</label>
	<input type="month" id="to_month">	
						
	<button id="go_button" class="btn btn-primary">Go</button>
</div>

<iframe src="/report/monthly-report" width="100%" height="100%">IFrame Not Supported!</iframe>

<link rel="stylesheet" type="text/css" href="/assets/css/reports.css">
<script type="text/javascript" src="/assets/js/reports.js"></script>