<div style="padding-bottom:15px">
	<div align="center">
		<strong>Monthly Receiving Report</strong> 
	</div>
	<br>
	<form>
		
		<label for="from_month">From Date</label>	
		<input type="date" id="from_month" required="required">
		
		<label for="to_month">To Date</label>
		<input type="date" id="to_month" required="required">	
		
		<button id="go_button" class="btn btn-primary">Go</button>
	</form>
</div>

<iframe src="/report/monthly-receiving-report" width="100%" height="100%">IFrame Not Supported!</iframe>

<link rel="stylesheet" type="text/css" href="/assets/css/reports.css">
<script type="text/javascript" src="/assets/js/reports.js"></script>
<script type="text/javascript">
    $('document').ready(function() {
        $('form').on('submit', function(e) {
            e.preventDefault();			
            var from_month = ($('#from_month').val())?$('#from_month').val():false;
            var to_month = ($('#to_month').val())?$('#to_month').val():false;
            var get = $('iframe')[0].src.split('/?')[0]+'/?from_month='+from_month+'&to_month='+to_month;
			
			if(from_month && to_month) {
                return $('iframe')[0].src=get;
            }
        });
    });
</script>