<div style="padding-bottom:15px">
	<div align="center">
		<strong>Old Reusable Stock</strong> 
	</div>
	<br>
	
	<label for="from_date">From Date</label>	
	<input type="date" id="from_date">
	
	<label for="to_date">To Date</label>
	<input type="date" id="to_date">	
						
	<button id="go_button" class="btn btn-primary">Go</button>
</div>

<iframe src="/report/old-reusable-stock" width="100%" height="100%">IFrame Not Supported!</iframe>

<link rel="stylesheet" type="text/css" href="/assets/css/reports.css">
<script type="text/javascript" src="/assets/js/reports.js"></script>