<div style="padding-bottom:15px">
	<div align="center">
		<strong>Requisition & Issue Slip</strong> 
	</div>
	<br>
	
	
	<label for="ris_no">RIS No</label>
	<input type="input" placeholder="Enter RIS No" id="ris_no">	
						
	<button id="go_button" class="btn btn-primary">Go</button>
</div>

<iframe src="/report/ris" width="100%" height="100%">IFrame Not Supported!</iframe>

<link rel="stylesheet" type="text/css" href="/assets/css/reports.css">
<script type="text/javascript" src="/assets/js/reports.js"></script>