<div style="padding-bottom:15px">
	<div align="center">
		<strong>Return Materials</strong> 
	</div>
	<br>
	
	
	<label for="rms_no">RM No</label>
	<input type="input" placeholder="Enter RM No" id="rms_no">	
						
						
	<button id="go_button" class="btn btn-primary">Go</button>
</div>

<iframe src="/report/rms" width="100%" height="100%">IFrame Not Supported!</iframe>

<link rel="stylesheet" type="text/css" href="/assets/css/reports.css">
<script type="text/javascript" src="/assets/js/reports.js"></script>