<!-- Sidebar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<img src="/assets/img/logo.png" alt="SWD Logo" style="width:50px;height:50px"> 
		<a class="navbar-brand" href="/">Silang Water District</a>
	</div>
	<?php if($page!='login'):
	?>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse" id="navigator">
		<ul class="nav navbar-nav side-nav" >
			<li class="active">
				<a href="/"><i class="fa fa-dashboard"></i> Home</a>
			</li>
			<li>
				<a href="/po"><i class="fa fa-bar-chart-o"></i> Purchase Order</a>
			</li>
			<li>
				<a href="/ia"><i class="fa fa-bar-chart-o"></i> Inspection / Acceptance</a>
			</li>
			<li>
				<a href="/supplier"><i class="fa fa-table"></i> Suppliers</a>
			</li>
			<li>
				<a href="/articles"><i class="fa fa-table"></i> Articles</a>
			</li>
			<li>
				<a href="/items"><i class="fa fa-table"></i> Items</a>
			</li>
			<li>
				<a href="/requisition"><i class="fa fa-table"></i> Requisition</a>
			</li>
			<li>
				<a href="/issuance"><i class="fa fa-table"></i> Issuance</a>
			</li>
			<li>
				<a href="/rm"><i class="fa fa-table"></i> Returned Materials</a>
			</li>
			<li class="dropdown sidebar">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-square-o-down"></i> Report(s) <b class="caret"></b></a>
				<ul class="dropdown-menu" id="reports-menu">
					<!--<li>
						<a href="/report/propery-code" target="report">Property Code</a>
					</li>-->
					
						
					<li>
						<a href="/report-filter/physical-count">Physical Count</a>
					</li>
					
					<li>
						<a href="/report-filter/bin-card">Bin Card</a>
					</li>
					<li>
						<a href="/report-filter/stock-card">Stock Card</a>
					</li>
					<li>
						<a href="/report-filter/issue-out">Materials and Supplies Issued</a>
					</li>					
					<li>
						<a href="/report-filter/monthly-report">Monthly Inventory</a>
					</li>
					<li>
						<a href="/report-filter/monthly-recieving">Monthly Receiving</a>
					</li>
					<li>
						<a href="/report-filter/ris">Requisition and Issue</a>
					</li>
					<li>
						<a href="/report-filter/rms">Returned Materials</a>
					</li>
					<li>
						<a href="/report-filter/old-reusable-stock">Old Reusable Stock</a>
					</li>
					<li>
						<a href="/report-filter/stock-card">Stock Card</a>
					</li>
				</ul>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right navbar-user">
			<li class="dropdown user-dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Administrator <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="/profile"><i class="fa fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="/settings"><i class="fa fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="/?logout"><i class="fa fa-power-off"></i> Log Out</a>
					</li>
				</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
	<?php endif; ?>
</nav>
