<!-- Sidebar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/">Silang Water District</a>
	</div>
	<?php if($page!='login'):
	?>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse" id="navigator">
		<ul class="nav navbar-nav side-nav">
			<li class="active">
				<a href="/"><i class="fa fa-dashboard"></i> Home</a>
			</li>
			<li>
				<a href="/po"><i class="fa fa-bar-chart-o"></i> Purchase Order</a>
			</li>
			<li>
				<a href="/ia"><i class="fa fa-bar-chart-o"></i> Inspection / Acceptance</a>
			</li>
			<li>
				<a href="/supplier"><i class="fa fa-table"></i> Supplier(s)</a>
			</li>
			<li>
				<a href="/items"><i class="fa fa-table"></i> Items</a>
			</li>
			<li>
				<a href="/ris"><i class="fa fa-font"></i> Requisition / Issue</a>
			</li>
			<li>
				<a href="/rm"><i class="fa fa-desktop"></i> Returned Materials</a>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-square-o-down"></i> Report(s) <b class="caret"></b></a>
				<ul class="dropdown-menu" id="reports-menu">
					<li>
						<a href="/report/propery-code" target="report">Property Code</a>
					</li>
					<li>
						<a href="/report/inventory-count" id="phy-inv-count" target="report">
							Physical Count
						</a>
					</li>
					<li>
						<a href="/report/bin-card" target="report">Bin Card</a>
					</li>
					<li>
						<a href="/report/issue-out" target="report">Issue Out</a>
					</li>
					<li>
						<a href="/report/rms" target="report">Issue Out</a>
					</li>
					
					<li>
						<a href="/report/monthly-report" target="report">Monthly Report</a>
					</li>
					<li>
						<a href="/report/monthly-report" target="report">Requisition and Issue</a>
					</li>
					<li>
						<a href="/report/monthly-report" target="report">Returned Materials</a>
					</li>
					<li>
						<a href="/report/old-reusable-stock" target="report">Old Reusable Stock</a>
					</li>
					<li>
						<a href="/report/stock-card" target="report">Old Reusable Stock</a>
					</li>
				</ul>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right navbar-user">
			<li class="dropdown user-dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Juan Dela Cruz <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="/profile"><i class="fa fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="/settings"><i class="fa fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="/logout"><i class="fa fa-power-off"></i> Log Out</a>
					</li>
				</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
	<?php endif; ?>
</nav>
<script type="text/javascript">
(function($) {
	$('#navigator li').removeClass('active');
	var path = window.location.pathname;
	$('a[href="' + path + '"]').parent().addClass('active');
	
	$('#reports-menu a').on('click', function(){
		$('div.body').remove();
		$('#page-wrapper').css({
			'padding':'0',
			'height':window.innerHeight.toString()+'px'
		});
		$('body').css({
			'overflow':'hidden'
		});
		$('iframe[name="report"]').show().css({
			'width':'100%',
			'height':'100%'
		});
	});
})(jQuery); 
</script>