<!-- Sidebar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/">Silang Water District</a>
	</div>
	<?php if($page!='login'):
	?>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse" id="navigator">
		<ul class="nav navbar-nav side-nav">
			<li class="active">
				<a href="/"><i class="fa fa-dashboard"></i> Home</a>
			</li>
			<li>
				<a href="/po"><i class="fa fa-bar-chart-o"></i> Purchase Order</a>
			</li>
			<li>
				<a href="/ia"><i class="fa fa-bar-chart-o"></i> Inspection / Acceptance</a>
			</li>
			<li>
				<a href="/supplier"><i class="fa fa-table"></i> Supplier(s)</a>
			</li>
			<li>
				<a href="/items"><i class="fa fa-edit"></i> Item(s)</a>
			</li>
			<li>
				<a href="/ris"><i class="fa fa-font"></i> Requisition / Issue</a>
			</li>
			<li>
				<a href="/rms"><i class="fa fa-desktop"></i> Returned Materials</a>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-square-o-down"></i> Report(s) <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="/report/ia">Inspection / Acceptance</a>
					</li>
					<li>
						<a href="/report/inventory-count">Physical Count on Inventory</a>
					</li>
					<li>
						<a href="/report/materials-inventory">Materials Inventory</a>
					</li>
					<li>
						<a href="/report/supplies-inventory">Supplies Inventory</a>
					</li>
					<li>
						<a href="/report/supplies-issued">Supplies Issued</a>
					</li>
				</ul>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right navbar-user">
			<li class="dropdown user-dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Juan Dela Cruz <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="/profile"><i class="fa fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="/settings"><i class="fa fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="/logout"><i class="fa fa-power-off"></i> Log Out</a>
					</li>
				</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
	<?php endif; ?>
</nav>
<script type="text/javascript">
	(function($) {
		$('#navigator li').removeClass('active');
		var path = window.location.pathname;
		$('a[href="' + path + '"]').parent().addClass('active');
	})(jQuery); 
</script>