<script type="text/html" id="action_tpl">
<div class="action">
	<!--<input type="hidden" vname="//model//_id" value="/model_id/"/>-->
	<div class="hidden_data"></div>
	<div class="btn-group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			Action <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			<li>
				<a href="#" data-toggle="modal" 
					data-target="#//target-modal//-modal"
					data-backdrop="static" data-keyboard="false"
					class="edit-//model//">
				Edit
				</a>
			</li>
			<li>
				<a href="///model///delete//model_id/"
					onclick="return confirm('Are you sure you want to delete this?')">
					Delete
				</a>
			</li>
			<li>
				<a href="#" data-toggle="modal"
					data-target="#//target-modal//-modal"
					data-backdrop="static" data-keyboard="false"
					class="view-//model//">
				View
				</a>
			</li>
		</ul>
	</div>
</div>
</script>