<style>
	.request-dept {
		padding-top: 10px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<h3>
			Inspection / Acceptance 
			<small>Inspection and Acceptance of the received item or materials.</small>
		</h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Inspection / Acceptance 
			</li>
		</ol>
	</div>
</div>
<div class="border">
	<div class="form-horizontal row">
		<div class="col-md-6">
			<div class="form-group">
			    <label class="col-sm-2 control-label">Supplier</label>
			    <div class="col-sm-10">
			      <input type="input" class="form-control" placeholder="Name">
			      <input type="hidden" name="po_supplier_id">
			    </div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
			    <label class="col-sm-2 control-label">IAR No.</label>
			    <div class="col-sm-4">
			      <input type="input" class="form-control" placeholder="Name">
			      <input type="hidden" name="po_supplier_id">
			    </div>
			</div>
		</div>
	</div>
	<div class="form-horizontal row">
		<div class="col-md-3">
			    <label class="control-label col-md-4">PO No.:</label>
			    <div class="col-md-8">
			      <input type="input" class="form-control" placeholder="Name">
			    </div>
		</div>
		<div class="col-md-2">
			    <label class="control-label col-md-3">Date:</label>
			    <div class="col-md-9">
			      <input type="input" class="form-control" placeholder="Name">
			    </div>
		</div>
		<div class="col-md-3">
			    <label class="control-label col-md-3">Inv. No:</label>
			    <div class="col-md-9">
			      <input type="input" class="form-control" placeholder="Name">
			    </div>
		</div>
		<div class="col-md-2">
		    <label class="control-label col-md-5">DR No.:</label>
		    <div class="col-md-7">
		      <input type="input" class="form-control" placeholder="Name">
		    </div>
		</div>
		<div class="col-md-2">
		    <label class=" control-label col-md-3">Date:</label>
		    <div class="col-md-9">
		      <input type="input" class="form-control" placeholder="Name"/>
		    </div>
		</div>
	</div>
	<div class="form-inline row request-dept">
		<div class="col-sm-11">
		    <label class="col-sm-2 control-label">Requesitioning Office/Dept:</label>
		    <div class="col-sm-6">
		      <input type="input" class="form-control" placeholder="Name">
		      <input type="hidden" name="po_supplier_id">
		    </div>
		</div>
	</div>
</div>
<div class="row item-list border-space">
	<div class="col-lg-12">
		<h4 align="center">Inspection/Acceptance List</h4>
		<div class="table-responsive">
			<table class="table table-hover table-striped table-bordered tablesorter">
				<thead>
					<tr>
						<th class="header">Stock No. <i class="fa fa-sort"></i></th>
						<th class="header">Unit <i class="fa fa-sort"></i></th>
						<th class="header">Description <i class="fa fa-sort"></i></th>
						<th class="header">Unit Cost <i class="fa fa-sort"></i></th>
						<th class="header">Total Amount <i class="fa fa-sort"></i></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="4" align="center">TOTAL</td>
						<td >228.00</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>1</td>
						<td>bag</td>
						<td>50</td>
						<td>Portland Cement</td>
						<td>228.00</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>