<style>
	.modal-dialog {
		width: 90%;
	}
	.ia .border {
		margin-top: 10px;
	}
	
	.ia .request-dept {
		padding-top: 10px;
	}
	
	.ia th:last-child {
		width: 5%;
	}
	
	.ia #ia-table td:nth-child(1){
		width: 15%;
	}
	.ia #ia-table td:nth-child(7){
		width: 10%;
	}
	.ia #ia-table td:nth-child(9),
	.ia #ia-table td:nth-child(2),
	.ia #ia-table td:nth-child(4),
	.ia #ia-table td:nth-child(5),
	.ia #ia-table td:nth-child(6),
	.ia #ia-dtl-table td:nth-child(3),
	.ia #ia-dtl-table td:nth-child(5),
	.ia #ia-dtl-table td:nth-child(6),
	.ia #ia-dtl-table tfoot td
	{
		text-align:right;
	}
	
		
	.dataTables_filter label{
		width:250px;
	}
	[name="ia-table_length"],[name="ia-dtl-table_length"]{
		display: inline;
		width: 100px;
		height: 34px;
		padding: 6px 12px;
		font-size: 14px;
		line-height: 1.428571429;
		color: #555555;
		vertical-align: middle;
		background-color: #ffffff;
		background-image: none;
		border: 1px solid #cccccc;
		border-radius: 4px;
	}
	.modal-body{
		max-height:600px;
		overflow-y:auto;
	}
</style>
<div class="row-fluid">
	<!--Page header-->
	<div class="col-lg-12">
		<h3> Inspection / Acceptance <small>Inspection and Acceptance of the received item or materials.</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Inspection / Acceptance
			</li>
		</ol>
		<?php include(dirname(__FILE__).'\_message.phtml'); ?>
	</div>
</div>
<!--  -->
<div class="row-fluid">
	<div class="col-xs-12">
		<button type="button" class="btn btn-primary pull-right" id="create-ia"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#ia-modal">
			Inspect
		</button>
	</div>
</div>
<div class="row-fluid border">
	<div class="col-sm-12 " style="padding-top:20px">
		<div class="table-responsive">
			<table class="table table-hover table-striped table-bordered tablesorter" id="ia-table">
				<thead>
					<tr>
						<th>Supplier</th>
						<th>PO No.</th>
						<th>PO Date</th>
						<th>IAR No.</th>
						<th>Inv. No.</th>
						<th>DR. No.</th>
						<th>IAR Date</th>
						<th>Requisitiong Office/Dept</th>
						<th>Total Amount</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					
				</tbody>
			</table>
		</div>
	</div>
</div>

<form method="post" action="/ia/furnish/" id="ia-modal-form">
<div class="modal fade" id="ia-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
			</div>
			<div class="modal-body">
				<input type="hidden" name="ia_id"/>
				<!---IA Proper -->
				<div class="border">
					<!--Page body-->
					<div class="form-horizontal row">		
						<div class="col-md-3">
							<label class="control-label col-md-3">PO No:</label>
							<div class="col-md-9">
								<input type="input" class="form-control" placeholder="PO No." id="po_no" required="required">
								<input type="hidden" name="ia_po_id" id="po_id">
							</div>
						</div>
						<div class="col-md-3">
							<label class="control-label col-md-3">PO Date:</label>
							<div class="col-md-9">
								<input type="input" class="form-control" placeholder="Date" id="po_created" disabled="disabled">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="col-sm-2 control-label">Supplier</label>
								<div class="col-sm-9">
									<input type="input" class="form-control" placeholder="Name" id="supplier_name" disabled="disabled">
								</div>
							</div>
						</div>								
					</div>
					<div class="form-horizontal row">
						<div class="col-md-3">
							<div class="form-group">
								<label class="col-sm-3 control-label">IAR No:</label>
								<div class="col-sm-7">
									<input type="input" class="form-control" placeholder="IAR No." name="ia_no" required="required">
								</div>
							</div>
						</div>						
						<div class="col-md-3">
							<label class="control-label col-md-3">Inv. No:</label>
							<div class="col-md-7">
								<input type="input" class="form-control" placeholder="Inv No." name="ia_inv_no">
							</div>
						</div>
						<div class="col-md-3">
							<label class="control-label col-md-3">DR No:</label>
							<div class="col-md-7">
								<input type="input" class="form-control" placeholder="Dr No." name="ia_dr_no">
							</div>
						</div>
					</div>
					<div class="form-horizontal row">
						<div class="col-md-3">
							<label class=" control-label col-md-3">IAR Date:</label>
							<div class="col-md-7">
								<input type="input" class="form-control" placeholder="Date" name="ia_created"/>
							</div>
						</div>
					
						<div class="form-group">
							<label class="col-sm-2 control-label">Inspection Date:</label>
							<div class="col-sm-2">
								<div class='input-group date ia-inspection'>
									<input type='text' name="ia_date_inspected" class="form-control" required="required"/>
									<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
									</span>
								</div>
							</div>
						</div>	
					</div>
					</div>					
					<div class="border row">
						<div class="col-sm-4">
							<label class="col-sm-4 control-label">Requesitioning Office/Dept:</label>
							<div class="col-sm-7">
								<select class="form-control" name="ia_dept_id" required="required">
								<option value="">Select Office/Dept</option>
								<?php if(!empty($depts)):?>
								<?php foreach($depts as $dept):?>
								<option value="<?php echo $dept['dept_id']; ?>"><?php echo $dept['dept_name']; ?></option>
								<?php endforeach;?>
								<?php endif;?>
								</select>
							</div>
						</div>
					</div>
				
				<hr/>
				<div class="row item-list border-space">
					<div class="col-lg-12">
						<h4 align="center">Inspected/Accepted List</h4>
						<table class="table table-hover table-striped table-bordered tablesorter" id="ia-dtl-table">
							<thead>
								<tr>
									<th>Stock No.</th>
									<th>Unit</th>
									<th>Qty</th>
									<th>Description</th>
									<th>Unit Cost</th>
									<th>Total Amount</th>
									<th>Action</th>
								</tr>
							</thead>
							<tfoot>
								<tr>
									<td colspan="5" align="center">TOTAL</td>
									<td id="ia_total_amount">0.00</td>
								</tr>
							</tfoot>
							<tbody></tbody>
						</table>
					</div>
				</div>
				<div class="row item-list border-space">
					<div class="col-lg-12">
						<div class="col-lg-6">
							<h4 align="center">INSPECTORS</h4>
							<div class="form-horizontal row inspectors">
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='1' vname="inspectors_name" >
									</div>
									<div class="col-md-5">
										<input type="hidden" class="form-control" placeholder="Position" order='1' vname="inspectors_position">
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='2' vname="inspectors_name" >
									</div>
									<div class="col-md-5">
										<input type="hidden" class="form-control" placeholder="Position" order='2' vname="inspectors_position">
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='3' vname="inspectors_name" >
									</div>
									<div class="col-md-5">
										<input type="hidden" class="form-control" placeholder="Position" order='3' vname="inspectors_position">
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='4' vname="inspectors_name" >
									</div>
									<div class="col-md-5">
										<input type="hidden" class="form-control" placeholder="Position" order='4' vname="inspectors_position">
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='5' vname="inspectors_name" >
									</div>
									<div class="col-md-5">
										<input type="hidden" class="form-control" placeholder="Position" order='5' vname="inspectors_position">
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='6' vname="inspectors_name" >
									</div>
									<div class="col-md-5">
										<input type="hidden" class="form-control" placeholder="Position" order='6' vname="inspectors_position">
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-6">
							<h4 align="center">ACCEPTEE</h4>
							<div class="form-horizontal row acceptee">
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='1' vname="acceptee_name">
									</div>
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Position" order='1' vname="acceptee_position" >
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='2' vname="acceptee_name">
									</div>
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Position" order='2' vname="acceptee_position" >
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='3' vname="acceptee_name">
									</div>
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Position" order='3' vname="acceptee_position" >
									</div>
								</div>
								<div class="col-md-12 row">
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Name" order='4' vname="acceptee_name">
									</div>
									<div class="col-md-5">
										<input type="input" class="form-control" placeholder="Position" order='4' vname="acceptee_position" >
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="hidden_data"></div>	
				<!-- IA Proper End -->
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="furnish">
						<span class="modal-form-action">Furnish</span>
					</button>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
</form>
<form id="ia_dtl-modal-form" action='#'>
<div class="modal fade" id="ia_dtl-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
			</div>
			<div class="modal-body">
				<div class="row border">
							<div class="border">
								<div class="col-sm-12">
									<label for="input-name" class="col-sm-2 control-label">Desc</label>
									<span class="form-group col-sm-10" id="po_dtl_item_desc">DESC</span>
								</div>
								<div class="col-sm-12">
									<label for="input-address" class="col-sm-2 control-label">Unit</label>
									<span class="form-group col-sm-3" id="po_dtl_item_unit">UNIT</span>
								</div>
								<div class="col-sm-12">
									<label for="input-tel" class="col-sm-2 control-label">Qty</label>
									<div class="form-group col-sm-3">
										<input type="text" class="form-control" placeholder="QTY"
											name="ia_dtl_item_qty" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-tel" class="col-sm-2 control-label">Cost</label>
									<span class="form-group col-sm-3" id="po_dtl_item_cost">COST</span>
								</div>
							</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default secondary" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="">
						<span class="modal-form-action" >Save changes</span>
					</button>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
</form>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/autocomplete.js"></script>
<script type="text/javascript" src="/assets/js/modal_control.js"></script>
<script type="text/javascript">
(function(){
	$('document').ready(function(){
		ia_table = {};
		ia_dtl_table = {};
		current_ia_dtl_row = {}; //<- eto oh
		current_ia_dtl = {} ;
		action_template = $('#action_tpl').text().trim();
		$('.ia-inspection').datetimepicker();
		
		var ia_columns = [
			            { "mData": "supplier_name" },
			            { "mData": "po_no" },
			            { "mData": function(data) {
			            	return moment(data.po_created).format('ddd, MMM Do YYYY');
			            }},
			            { 'mData': 'ia_no' },
			            { 'mData': 'ia_inv_no'},
			            { 'mData': 'ia_dr_no' },
			            { 'mData': function(data){
								return moment(data.ia_created).format('ddd, MMM Do YYYY');
						}},
			            { 'mData': 'dept_name' },
			            { 'mData': function(data){
			            	return parseFloat(data.ia_total_amount).moneyFormat();	
			            } },
			            {
			            	'mData': function(data){
			            		var model = new RegExp('//model//','g');
			            		var model_id = new RegExp('/model_id/','g'); 
			            		var target_modal = new RegExp('//target-modal//','g'); 
								var action = action_template
									.replace(model, 'ia')
									.replace(target_modal, 'ia')
									.replace(model_id, data.ia_id);
			            		action = $(action).clone();
								action.find('a.edit-ia').parent().remove();
								action.find('a.delete-ia').parent().remove();
								action.find('ul.dropdown-menu').append(
								'<li><a class="print_report-ia" href="/ia/report/'+data.ia_id+
									'" target="_blank" title="Print from pdf file.">Print</a></li>'
								);
								action = action.html();
								return action;
			            	}
			            }];
		
		ia_dtl_columns = [
				{ "mData": function(data){ //stock_no 
					if(data.po_dtl_stock_no){
						return data.po_dtl_stock_no;
					}
					return " "; 
				}},
	            { "mData": "po_dtl_item_unit" },
	            { "mData": function(data) { //ia_qty
					if(data.ia_dtl_item_qty) {
						return data.ia_dtl_item_qty;
					}
					return " ";
				}},
	            { "mData": "po_dtl_item_desc" },
	            { "mData": function(data){ // po_dtl_unit_cost
	            	return parseFloat(data.po_dtl_item_cost).moneyFormat();
	            }},
	            { "mData": function(data) { // total amount
					if(data.ia_dtl_item_qty) {
						var total_amount = parseFloat(data.ia_dtl_item_qty*parseFloat(data.po_dtl_item_cost));
						return parseFloat(total_amount).moneyFormat();
					}
					return ' ';
	            }},
	            { 'mData': function(data){
						var model = new RegExp('//model//','g');
						var model_id = new RegExp('/model_id/','g'); 
						var target_modal = new RegExp('//target-modal//','g'); 
						
						var action = action_template
							.replace(model, 'ia_dtl')
							.replace(target_modal, 'ia_dtl')
							.replace(model_id, data.ia_dtl_id);
						action = $(action).clone();
						action.find('a.edit-ia_dtl').text('Inspect');
						action.find('a.delete-ia_dtl').parent().remove();
						action = action.html();
						return action;
				}}
			];
		
		ia_mapping = function(value, obj) {
			switch(value) {
				case 'ia_date_inspected':
					return moment(obj[value]).format('M/D/YYYY');
				case 'ia_date_received':
					return moment(obj[value]).format('ddd, MMM Do YYYY');
				case 'ia_created':
					return moment(obj[value]).format('M/D/YYYY');
				case 'po_created':
					return moment(obj[value]).format('M/D/YYYY');
				case 'ia_total_amount':
					return parseFloat(obj[value]).moneyFormat();
				default:
					return obj[value];
			};
		};
		
		ia_table = $('#ia-table').dataTable({
				'sPaginationType' : "two_button",
				"iDisplayLength" : 10,
				"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
				'sAjaxSource': '/ia/',
				'sAjaxDataProp': 'data',
				"aoColumns": ia_columns,
				"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
				  oSettings.jqXHR = $.ajax( {
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": {ia:'all'},
					"success": fnCallback
				  } );
				}
		});
		
		//IA DETAIL INIT
		ia_dtl_table = $('#ia-dtl-table').dataTable({
			"sPaginationType" : "two_button",
			"iDisplayLength" : 3,
			"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
			"bAutoWidth": false
		});

		//ACTION HANDLER
		$(document).on('click','a',function(){
			var action_handle = $(this);
			var row = action_handle.parents('tr:first');
			var  ia_id;
			
			//VIEW IA
			if(action_handle.hasClass('view-ia')) {
				var row_position = ia_table.fnGetPosition(row[0]); 
				var row_data = ia_table.fnGetData(row[0]);
				current_ia = row_data;
				current_ia_row = row_position;
				changeModal({
					'action':'/ia',
					'model':'ia',
					'submit_name': 'view-ia',
					'pr_button':'Back To List',
					'modal_label': 'View Inspection/Acceptance',
					'run': function(){						
						populate({
							'data': current_ia,
							'name':'ia',
							'map': ia_mapping },
							function(){
								console.log(current_ia.signatories);
								var ictr = 1;
								var actr = 1;
								$.each(current_ia.signatories,function(a,b){
									if(b.type == 'inspectors'){
										$('input[vname="inspectors_name"][order="'+ictr+'"]').val(b.name);
										ictr++;
									}
									if(b.type == 'acceptee'){
										$('input[vname="acceptee_name"][order="'+actr+'"]').val(b.name);
										$('input[vname="acceptee_position"][order="'+actr+'"]').val(b.position);
										actr++;
									}
								});
								$.each(Object.keys(current_ia), function(i, v){
									$('#ia-modal-form').find('input[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#ia-modal-form').find('select').attr('disabled', 'disabled');
									$('#'+v)
										.attr('disabled', 'disabled');
								});
								ia_dtl_table = $('#ia-dtl-table').dataTable({
										"sPaginationType" : "two_button",
										"iDisplayLength" : 3,
										"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
										'sAjaxSource': '/ia/',
										'sAjaxDataProp': 'data',
										"bDestroy" : true,
										"bAutoWidth": false,
										"aoColumns": ia_dtl_columns,
										"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
										  oSettings.jqXHR = $.ajax( {
											"dataType": 'json',
											"type": "POST",
											"url": sSource,
											"data": {ia:current_ia['ia_id']},
											"success": fnCallback
										  } );
										}
									});
								var bVis = ia_dtl_table.fnSettings().aoColumns[6].bVisible;
								ia_dtl_table.fnSetColumnVis( 6, bVis ? false : true );
							});
					}
				});
			}
			//IF EDITING DETAIL
			if(action_handle.hasClass('edit-ia_dtl')) {
				var row_position = ia_dtl_table.fnGetPosition(row[0]); 
				var row_data = ia_dtl_table.fnGetData(row[0]);
				current_ia_dtl = row_data;
				current_ia_dtl_row = row_position;
				
				//MODIFY MODAL FOR EDIT MODE
				changeModal({
					'action':'#',
					'model':'ia_dtl',
					'submit_name': 'edit-ia_dtl',
					'pr_button':'Save Changes',
					'modal_label': 'Accepted Item Quantity',
					'run': function() {
						clear_form('ia_dtl');
						//POPULATE TO THE FORM
						populate({
							'data': row_data,
							'name':'ia_dtl',
							'map': function(v, o) {	return o[v]; }});
						
					}
				});
			}
			//IF VIEWING DETAIL
			if(action_handle.hasClass('view-ia_dtl')) {
				var row_position = ia_dtl_table.fnGetPosition(row[0]); 
				var row_data = ia_dtl_table.fnGetData(row[0]);
				current_ia_dtl = row_data;
				current_ia_dtl_row = row_position;
				changeModal({
					'action':'#',
					'model':'ia_dtl',
					'submit_name': 'view-ia_dtl',
					'pr_button':'Back to Inspection/Acceptance',
					'modal_label': 'View Inspected/Accepted Item',
					'run': function() {
						populate({
							'data': current_ia_dtl,
							'name':'ia_dtl',
							'map': function(v, o) { return o[v]; }},
							function(){
								$('#ia_dtl-modal-form .secondary').hide();
								$('#ia_dtl-modal-form').find('input').attr('disabled','disabled');
							}
						);
						
						
					}
				});
			}
		});		
	
		//DETAIL SUBMIT HANDLER
		$('#ia_dtl-modal-form').submit(function(e){
			var form = $(this);
			var button_action = form.find('.btn-primary').attr('name');
			e.preventDefault();
			
			var inputs = form.find('input[name]');
			var items = ia_dtl_table.fnGetData();
			var totalCosting = 0;									
			switch(button_action){
				case 'edit-ia_dtl':
					$.each(inputs, function(i, o) {
						if (current_ia_dtl[$(o).attr('name')]!= 'undefined') {
							current_ia_dtl[$(o).attr('name')] = $(o).val();
						}
						/*if($['ia_dtl_item_qty']!= 'undefined'){
							totalCosting+=(parseInt(items[i1]['ia_dtl_item_qty'])*
								parseFloat(items[i1]['po_dtl_item_cost']))
						}*/
					});
					ia_dtl_table.fnUpdate(current_ia_dtl, current_ia_dtl_row);
					break;
				default:
					break;
			};
			var total_amount = 0;
			items = ia_dtl_table.fnGetData();
			(items).forEach(function(v, i, a){
				console.log(v);
				if(v['ia_dtl_item_qty'] != undefined) {
					console.log(parseFloat(v['po_dtl_item_cost'])
						*parseInt(v['ia_dtl_item_qty']));
					total_amount +=parseFloat(v['po_dtl_item_cost'])
						*parseInt(v['ia_dtl_item_qty']);
				}
			});
			$('#ia_total_amount').text(parseFloat(total_amount).moneyFormat());
			$('#ia_dtl-modal').modal('hide');
			$('#ia_dtl-modal-form').find('input').removeAttr('disabled');
		});
		
		//HEADER SUBMIT HANDLER
		$('#ia-modal-form').submit(function(e){
			//e.preventDefault();
			
			$('#hidden_data').html('');
			var data = ia_dtl_table.fnGetData();
			
			$.each(data, function(index, o){
				(Object.keys(o)).forEach(function(v, i, a){
						switch(v){
							case 'po_dtl_id':
								data[index]['ia_dtl_po_dtl_id'] = data[index][v];
								delete data[index][v];
							break;
							case 'ia_po_dtl_id':break;
							case 'po_dtl_item_qty':break;
							case 'po_dtl_item_cost':break;
							case 'ia_dtl_id':break;
							case 'ia_dtl_item_qty':break;
							case 'ia_dtl_item_created':break;
							default:
								delete data[index][v];
							break;
						}
				});
			});
			
			console.log(data);
			
			var hidden_aggregation = $('#hidden_data');
			$.each(data, function(index, o){
				Object.keys(o).forEach(function(v,i,a){
					hidden_aggregation.append(
						'<input type="hidden" name="ia_dtl['+index+']['+v+']" value="'+o[v]+'"/>');
					});
			});
			
			//inspectator
			$.each($('.inspectors .row'),function(i,e){
				var name = $(e).find('input[vname="inspectors_name"]').val();
				var position = $(e).find('input[vname="inspectors_position"]').val();
				hidden_aggregation.append('<input type="hidden" name="ia_signatories['+i+'][name]" value="'+name+'"/>');
				hidden_aggregation.append('<input type="hidden" name="ia_signatories['+i+'][position]" value="'+position+'"/>');
			});
			
			//inspectator
			$.each($('.acceptee .row'),function(i,e){
				var name = $(e).find('input[vname="acceptee_name"]').val();
				var position = $(e).find('input[vname="acceptee_position"]').val();
				hidden_aggregation.append('<input type="hidden" name="ia_signatories_acceptee['+i+'][name]" value="'+name+'"/>');
				hidden_aggregation.append('<input type="hidden" name="ia_signatories_acceptee['+i+'][position]" value="'+position+'"/>');
			});
			
		});
		
		//CREATE PO
		$('#create-ia').click(function(){
			ia_dtl_table.fnClearTable();
			changeModal({
					'action':'/ia/furnish',
					'model':'ia',
					'submit_name': '',
					'pr_button':'Accept',
					'modal_label': 'Create Inspection/Acceptance',
					'run': function(){
						clear_form('ia', function(){
							$('input[name="ia_created"]').val(new Date().toDateString());
							$('#po_no').removeAttr('disabled');
						});
						ia_dtl_table = $('#ia-dtl-table').dataTable({
								"sPaginationType" : "two_button",
								"iDisplayLength" : 3,
								"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
								"bDestroy" : true,
								"bAutoWidth": false,
								"aoColumns": ia_dtl_columns
								});
						var bVis = ia_dtl_table.fnSettings().aoColumns[6].bVisible;
						ia_dtl_table.fnSetColumnVis( 6, bVis ? true : false );
					}
				});
		});
		
		//PO POPULATION
		$('#po_no').on('blur', function(){
			var input = $(this);
			var po_number = input.val();
			var having_ia_no = $('input[name="ia_no"]').val();
			clear_form('ia', function(){
				$('input[name="ia_created"]').val(moment().format('M/D/YYYY'));
				$('input[name="ia_no"]').val(having_ia_no);
			});
			$.post('/po/', {po_no : po_number}, function(data){
				po = (data.data)?data.data:false;
				if(!po.po_dtl.length) {
					alert('Purchase Order '+po_number+' not existing!');
					input.empty().focus();
				}
				if(po){
					po.po_is_furnished = parseInt(po.po_is_furnished); 
					po.po_is_cancelled = parseInt(po.po_is_cancelled); 
					if(po.po_is_furnished){
						alert('Purchase Order '+po.po_no+' is already inspected, accepted and completed!');
						input.empty().focus();
					}
					if(!po.po_is_furnished && !po.po_is_cancelled){
						populate({
							name:'ia',
							data: po,
							map: function(v,o){ 
								if(v == 'po_created') {
									return moment(v[o]).format('M/D/YYYY');
								}
								return o[v];
							}
						}, function(){
								ia_dtl_table = $('#ia-dtl-table').dataTable({
										'sPaginationType' : "two_button",
										"iDisplayLength" : 10,
										"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
										'sAjaxSource': '/po/',
										'sAjaxDataProp': 'data.po_dtl',
										"aoColumns": ia_dtl_columns,
										"bDestroy" : true,
										"bAutoWidth": false,
										"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
										  oSettings.jqXHR = $.ajax( {
											"dataType": 'json',
											"type": "POST",
											"url": sSource,
											"data": {po_no:po.po_no},
											"success": fnCallback
										  } );
										}
								});
						
						});
						
						
					}
				}
			});
		});
				
	})

}(jQuery));
</script>