<style>
.items .border {
	margin-top: 10px;
}
	
.dataTables_filter label{
	width:250px;
}
[name="item-table_length"]{
	display: inline;
	width: 100px;
	height: 34px;
	padding: 6px 12px;
	font-size: 14px;
	line-height: 1.428571429;
	color: #555555;
	vertical-align: middle;
	background-color: #ffffff;
	background-image: none;
	border: 1px solid #cccccc;
	border-radius: 4px;
}


.modal-body{
	max-height:450px;
	overflow-y:auto;
}
</style>
<div class="row-fluid">
	<div class="col-md-12">
		<h3>Items <small>Supplies / Materials </small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/">
					<i class="icon-dashboard"></i>
					Inventory
				</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i>
				Item
			</li>
		</ol>
		<?php include(dirname(__FILE__).'\_message.phtml'); ?>
	</div>
</div>
<div class="row-fluid">
	<div class="col-xs-12">
		<button type="button" class="btn btn-primary pull-right" id="create-item"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#item-modal">
			Create
		</button>
	</div>
</div>
<div class="border">
	<div class="row-fluid item-list border-space">
		<div class="col-md-12">
			<h4 align="center">Items List</h4>
			<div class="table-responsive">
				<table class="table table-hover table-striped table-bordered tablesorter" id="item-table">
					<thead>
						<tr>
							<th>Article</th>
							<th>Image</th>
							<th>Description</th>
							<th>Size</th>
							<th>Acct No.</th>
							<th>Stock No.</th>
							<th>Type</th>
							<th>Qty</th>
							<th>Unit</th>
							<th>Unit Cost</th>
							<th>Remarks</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- Modal -->
<form class="form-horizontal" role="form" action="" method="post" name="add-item" id="item-modal-form">
<div class="modal fade" id="item-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
      </div>
	  <div class="modal-body">
			<input type="hidden" name="item_id"/>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Stock No.:</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control" placeholder="Stock No" name="item_stock_no">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Acct No.:</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control" placeholder="Acct No" name="item_acct_no">
		    </div>
		  </div>
		  <div class="form-group ">
		    <label for="input-name" class="col-md-2 control-label">Desc:</label>
		    <div class="col-md-10">
		      <input type="text" class="form-control"  placeholder="Description" name="item_desc" required="required">
		    </div>
		  </div>
		  <div class="form-group ">
		    <label for="input-name" class="col-md-2 control-label">Size:</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control"  placeholder="Size" name="item_size">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-address" class="col-md-2 control-label">Unit:</label>
		    <div class="col-md-3">
		      <input type="text" class="form-control"  placeholder="Unit" name="item_unit_measure" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label class="col-md-2 control-label">Qty:</label>
		    <div class="col-md-2">
		      <input type="text" class="form-control"  placeholder="Qty" name="item_qty" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label class="col-md-2 control-label">Unit Cost:</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control"  placeholder="00.00" name="item_cost_unit_cost" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Article:</label>
		    <div class="col-md-10">
		      <select class="form-control" name="item_article_id">
					<option value="">
						Select Article
					</option>
				<?php if(isset($articles) && !empty($articles)): ?>
				<?php foreach($articles as $article): ?>
					<option value="<?php echo $article['article_id']; ?>">
						<?php echo $article['article_name']; ?>
					</option>
				<?php endforeach; ?>
				<?php endif; ?>
			  </select>
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Remarks:</label>
		    <div class="col-md-10">
		      <textarea type="te" class="form-control" placeholder="Remarks" name="item_remarks"></textarea>
		    </div>
		  </div>		
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" name=""><span class="modal-form-action">Save changes</span></button>
      </div>
    </div>
  </div>
</div>
</form>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/autocomplete.js"></script>
<script type="text/javascript" src="/assets/js/modal_control.js"></script>
<script type="text/javascript">
(function($) {
	$('document').ready(function(){
		current_item_row = {};
		current_item = {} ;
		action_template = $('#action_tpl').text().trim();
		
		item_columns = [
			{ "mData": "article_name" },
			{ "mData": function(data){
					return '<img class="item_img" src="/assets/img/item_images/'+data.item_stock_no+'.jpg" onerror="this.src=\'/assets/img/item_images/none.png\'" width="100" height="100"/>';
			}},
			{ "mData": "item_desc" },
			{ "mData": "item_size" },
			{ "mData": "item_acct_no" },
			{ "mData": "item_stock_no" },
			{ 'mData': "article_inventory_type" }, 
			{ 'mData': 'item_qty' },
			{ 'mData': 'item_unit_measure'},
			{ 'mData': function(data){ //ITEM UNIT COST
				return parseFloat(data.item_cost_unit_cost).moneyFormat();
			}},
			{ 'mData': 'item_remarks' },
			{ 'mData': function(data){
					var model = new RegExp('//model//','g');
					var model_id = new RegExp('/model_id/','g'); 
					var target_modal = new RegExp('//target-modal//','g'); 
					var action = action_template
						.replace(model, 'item')
						.replace(target_modal, 'item')
						.replace(model_id, data.item_id);
					return action;
				}
			}];
		
		item_tbl = $('#item-table').dataTable({
				'sPaginationType' : "two_button",
				"iDisplayLength" : 100,
				"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
				'sAjaxSource': '/items/',
				'sAjaxDataProp': 'data',
				"aoColumns": item_columns,
				"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
				  oSettings.jqXHR = $.ajax( {
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": {item:'all'},
					"success": fnCallback
				  } );
				}
		});
	
		item_mapping = function(value, obj){
			switch(value) {
				case 'item_cost_unit_cost':
					return parseFloat(obj[value]).moneyFormat();
				default:
					return obj[value];
			};
		}
		
		//ACTION HANDLER
		$(document).on('click','a',function(){
			var action_handle = $(this);
			var row = action_handle.parents('tr:first');
			clear_form('item');
			//EDIT ITEM
			if(action_handle.hasClass('edit-item')) {
				var row_position = item_tbl.fnGetPosition(row[0]); 
				var row_data = item_tbl.fnGetData(row[0]);
				current_item = row_data;
				current_item_row = row_position;
				changeModal({
					'action':'/item/edit',
					'model':'item',
					'submit_name': 'edit-item',
					'pr_button':'Save Changes',
					'modal_label': 'Edit Item',
					'run': function(){
						populate({
							'data': current_item,
							'name':'item',
							'map': item_mapping, 
						});	
					}
				});
				$('input[name="item_qty"],input[name="item_cost_unit_cost"]').attr("disabled","disabled");
			}
			//VIEW ITEM
			if(action_handle.hasClass('view-item')) {
				var row_position = item_tbl.fnGetPosition(row[0]); 
				var row_data = item_tbl.fnGetData(row[0]);
				current_item = row_data;
				current_item_row = row_position;
				changeModal({
					'action':'/item/#',
					'model':'item',
					'submit_name': 'view-item',
					'pr_button':'Back To List',
					'modal_label': 'View Item',
					'run': function(){
						$('.secondary').hide();
						
						populate({
							'data': current_item,
							'name':'item',
							'map': item_mapping },
							function(){
								$.each(Object.keys(current_item), function(i, v){
									$('#item-modal-form').find('input[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#item-modal-form').find('select[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#item-modal-form').find('textarea[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#'+v).attr('disabled', 'disabled');
								});
						});
					}
				});
			}
		});		
	
		//CREATE PO
		$('#create-item').click(function(){
			changeModal({
					'action':'/item/create',
					'model':'item',
					'submit_name': '',
					'pr_button':'Create',
					'modal_label': 'Create Item',
					'run': function(){
						clear_form('item');
					}
				});
		});
	
	});	
})(jQuery);
</script>