<style>
.items .border {
		margin-top: 10px;
	}
</style>
<div class="row">
	<div class="col-md-12">
		<h3>Items <small>Supplies / Materials </small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/">
					<i class="icon-dashboard"></i>
					Inventory
				</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i>
				Item
			</li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-xs-offset-10 col-xs-2">
		<button type="button" class="btn btn-primary" id="create-item"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#item-modal">
			Create
		</button>
	</div>
</div>
<div class="border">
	<div class="row item-list border-space">
		<div class="col-md-12">
			<h4 align="center">Items List</h4>
			<div class="table-responsive">
				<table class="table table-hover table-striped table-bordered tablesorter" id="item-table">
					<thead>
						<tr>
							<th>Article</th>
							<th>Description</th>
							<th>Stock No.</th>
							<th>Type</th>
							<th>Unit Of Measure</th>
							<th>Qty</th>
							<th>Cost</th>
							<th>Remarks</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="item-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
      </div>
      <form class="form-horizontal" role="form" action="" method="post" name="add-item" id="item-modal-form">
	  <div class="modal-body">
			<input type="hidden" name="item_id"/>
		  <div class="form-group ">
		    <label for="input-name" class="col-md-2 control-label">Desc:</label>
		    <div class="col-md-10">
		      <input type="text" class="form-control"  placeholder="Description" name="item_desc" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-address" class="col-md-2 control-label">Unit:</label>
		    <div class="col-md-3">
		      <input type="text" class="form-control"  placeholder="Unit" name="item_unit_measure" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label class="col-md-2 control-label">Qty:</label>
		    <div class="col-md-2">
		      <input type="text" class="form-control"  placeholder="Qty" name="item_qty" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Stock No.:</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control" placeholder="Stock No" name="item_stock_no">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Type :</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control" placeholder="Type" name="item_item_type">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Article:</label>
		    <div class="col-md-4">
		      <input type="text" class="form-control" placeholder="Article" name="item_article">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-md-2 control-label">Remarks:</label>
		    <div class="col-md-4">
		      <textarea type="te" class="form-control" placeholder="Remarks" name="item_remarks"></textarea>
		    </div>
		  </div>		
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" name=""><span class="modal-form-action">Save changes</span></button>
      </div>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
(function($) {
	
})(jQuery);
</script>