<style>
	body {
		background: #c5deea; /* Old browsers */
		background: -moz-radial-gradient(center, ellipse cover,  #c5deea 0%, #8abbd7 31%, #066dab 100%); /* FF3.6+ */
		background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,#c5deea), color-stop(31%,#8abbd7), color-stop(100%,#066dab)); /* Chrome,Safari4+ */
		background: -webkit-radial-gradient(center, ellipse cover,  #c5deea 0%,#8abbd7 31%,#066dab 100%); /* Chrome10+,Safari5.1+ */
		background: -o-radial-gradient(center, ellipse cover,  #c5deea 0%,#8abbd7 31%,#066dab 100%); /* Opera 12+ */
		background: -ms-radial-gradient(center, ellipse cover,  #c5deea 0%,#8abbd7 31%,#066dab 100%); /* IE10+ */
		background: radial-gradient(ellipse at center,  #c5deea 0%,#8abbd7 31%,#066dab 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#c5deea', endColorstr='#066dab',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
	}
	
	.panel-body {
		background: url("/assets/img/animated_water.gif") no-repeat scroll center center / cover  rgba(0, 0, 0, 0);
		box-shadow: 0px 7px 15px;
		height: 450px;
	}
	
	.panel-heading {
		box-shadow: -1px 0px 15px;	
	}
	
	.panel-inner { margin-top: 20%; }	

	#wrapper { padding-left: 0px; }
	
	.login-panel { margin-top: 20%; }
	
	.checkbox { display: inline-block; }
	
	.checkbox label { color: whitesmoke; }
	
	.form-control, .btn-block  { opacity: 0.7; }
</style>

<div align="center"	>
	<h1 class="panel-title" style="font-size:35px; color:white">Silang Water District</h1>
	<h1 class="panel-title" style="font-size:24px; color:white">SWD Warehouse Inventory System</h1>
	<img src="/assets/img/logo.png" alt="SWD Logo" style="width:150px;height:150px">
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Please Sign In</h3>
				</div>
				<div class="panel-body">
					<div class="panel-inner">
						<form role="form" method="post" action="/login">
							<fieldset>
								<div class="form-group">
									<input type="text" autofocus="" name="username" placeholder="Username" class="form-control" autocomplete="off">
								</div>
								<div class="form-group">
									<input type="password" value="" name="password" placeholder="Password" class="form-control">
								</div>
								<!-- Change this to a button or input when using this as a form -->
								<button class="btn btn-lg btn-success btn-block" href="">Login</button>
							</fieldset>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<footer>
  <p style="color:black; position:absolute; left:0px; bottom:30px">Powered: XNS Software Development Team</p>
  <p style="color:black; position:absolute; left:0px; bottom:15px">Project Initiated By: SWD Warehouse Inventory Department</p>
  <p style="color:black; position:absolute; left:0px; bottom:0px">Headed By: Mary Grace Baybay</p>
</footer>