<style>
	.po-modal-dialog {
		width: 75%;
	}
	.po .border {
		margin-top: 10px;
	}

	#po-table td:first-child {
		text-align: left;
	}
	
	#po-table th:first-child {
		width: 15%;
	}
	
	#po-table th:nth-child(2), #po-table th:nth-child(3), #po-table th:nth-child(4) {
		width: 10%;
	}
	
	#po-dtl-modal .modal-content {
    	margin-top: 30%;
	}
	
	#po-dtl-modal .modal-footer {
    	margin-top: 40%;
	}
	
</style>
<div class="row">
	<div class="col-sm-12">
		<h3>Purchase Order <small>Supplies and materials order to be purchased.</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Purchase Order
			</li>
		</ol>
	</div>
</div>
<div class="form-inline row">
	<div class="col-sm-offset-10 col-sm-2">
		<button type="button" class="btn btn-primary" id="create-po"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#po-modal">
			Create Order
		</button>
	</div>
</div>
<div class="row border">
	<div class="col-sm-12">
		<div class="table-responsive">
			<table class="table table-hover table-striped table-bordered tablesorter" id="po-table">
				<thead>
					<tr>
						<th>Supplier</th>
						<th>PO No.</th>
						<th>Date</th>
						<th>Procurement Mode</th>
						<th>Total Cost</th>
						<th>Delivery Place</th>
						<th>Delivery Date</th>
						<th>Delivery Term</th>
						<th>Payment Term</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="po-modal" tabindex="-1" role="dialog" 
	aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog po-modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label">
					<span class="modal-form-state">Action Here</span>
				</h4>
			</div>
			<div class="modal-body">
				<form method="post" action="/po/furnish/" id="po-modal-form">
					<div class="border">
						<div class="form-horizontal row">
							<div class="col-sm-7">
								<div class="form-group">
									<label class="col-sm-2 control-label">Supplier</label>
									<div class="col-sm-10">
										<input type="input" class="form-control" placeholder="Name" id="supplier_name">
										<input type="hidden" name="po_supplier_id" >
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Address</label>
									<div class="col-sm-10">
										<input type="input" class="form-control" placeholder="Address" id="supplier_address" disabled>
									</div>
								</div>
							</div>
							<div class="col-sm-5">
								<div class="form-group">
									<label class="col-sm-4 control-label">P.O. No.</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" name="po_no" placeholder="P.O. No.">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Date</label>
									<div class="col-sm-5">
										<input type="date" class="form-control" name="po_created" value="<?php echo date('F j, Y'); ?>" >
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Mode of Procurement</label>
									<div class="col-sm-5">
										<input type="text" class="form-control" placeholder="Mode" name="po_proc_mod">
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="border">
						<div class="form-horizontal row">
							<div class="col-sm-7">
								<div class="form-group">
									<label class="col-sm-2 control-label">Delivery Place</label>
									<div class="col-sm-4">
										<input type="input" class="form-control" placeholder="Place" name="po_deliv_place">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Delivery Date</label>
									<div class="col-sm-6">
										<input type="date" class="form-control" placeholder="Date" name="po_deliv_date">
									</div>
								</div>
							</div>
							<div class="col-sm-5">
								<div class="form-group">
									<label class="col-sm-4 control-label">Delivery Term</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" placeholder="Term" name="po_deliv_term">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Payment Term</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" placeholder="Term" name="po_pay_term">
									</div>
								</div>
							</div>
						</div>
					</div>
					<hr/>
					<div class="border">
						<div class="row item-input col-sm-12">
							<div class="col-sm-offset-11 col-sm-1">
								<button type="button" class="btn btn-primary" id="add-to-purchase"
								data-toggle="modal" data-target="#po-dtl-modal" data-backdrop="static" data-keyboard="false">
									Add Item
								</button>
							</div>
						</div>
					</div>
					<div class="row border-space">
						<div class="col-sm-12">
							<h4 align="center">Purchase List</h4>
							<div class="table-responsive">
								<table class="table table-hover table-striped table-bordered tablesorter" id="po-dtl-table">
									<thead>
										<tr>
											<th>Item No.</th>
											<th>Item Unit</th>
											<th>Quantity</th>
											<th>Description</th>
											<th>Unit Cost</th>
											<th>Amount</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody></tbody>
								</table>
							</div>
						</div>
					</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default secondary" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="furnish">
						<span class="modal-form-action">Furnish</span>
					</button>
				</div>
			</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="po-dtl-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
			</div>
			<div class="modal-body">
				<div class="border">
					<form id="po_dtl-modal-form" action='#'>
							<div class="border">
								<div class="col-sm-12">
									<label for="input-name" class="col-sm-2 control-label">Desc</label>
									<div class="form-group col-sm-10">	
										<input type="text" class="form-control" placeholder="Desc"
											name="po_dtl_item_desc" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-address" class="col-sm-2 control-label">Unit</label>
									<div class="form-group col-sm-3">
										<input type="text" class="form-control" placeholder="Unit"
											name="po_dtl_item_unit" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-tel" class="col-sm-2 control-label">Qty</label>
									<div class="form-group col-sm-3">
										<input type="text" class="form-control" placeholder="QTY"
											name="po_dtl_item_qty" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-tel" class="col-sm-2 control-label">Cost</label>
									<div class="form-group col-sm-3" required="required">
										<input type="text" class="form-control" placeholder="Unit Cost" name="po_dtl_item_cost">
									</div>
								</div>
							</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default secondary" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="">
						<span class="modal-form-action" >Save changes</span>
					</button>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/autocomplete.js"></script>
<script type="text/javascript" src="/assets/js/modal_control.js"></script>
<script type="text/javascript">
	(function($) {
		cache = {};
		po_dtl_counter = 0;
		current_po = 'new';
		poDtlTable = {};
		$('document').ready(function() {
			var actionTemplate = $('#action_tpl').text().trim();
			cache['po']={};
			
			var poTable = $('#po-table').dataTable({
				'sPaginationType' : "two_button",
				"iDisplayLength" : 10,
				"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
				'sAjaxSource': '/po/',
				'sAjaxDataProp': 'data',
				"aoColumns": [
			            { "mData": "supplier_name" },
			            { "mData": "po_no" },
			            { "mData": function(data) {
			            	return (new Date(new Date(data.po_created.split(' ')[0])
			            					.toDateString()+' '+data.po_created.split(' ')[1])
			            					.toDateString());
			            	}},
			            { "mData": "po_proc_mod" },
			            { "mData": "po_total" },
			            { "mData": "po_deliv_place" },
			            { "mData": function(data) {
			            	return (new Date(data.po_deliv_date).toDateString());
			            	}},
			            { "mData": "po_deliv_term" },
			            { "mData": "po_pay_term" },
			            {
			            	'mData': function(data){
			            		var model = new RegExp('//model//','g');
			            		var model_id = new RegExp('/model_id/','g'); 
			            		var target_modal = new RegExp('//target-modal//','g'); 
								var action = actionTemplate
									.replace(model, 'po')
									.replace(target_modal, 'po-modal')
									.replace(model_id, data.po_id);
								if(typeof(cache['po'][data.po_id]) == "undefined") {
									cache['po'][data.po_id] = data;
								}
			            		return action;
			            	}
			            }]
			});

			poDtlTable = $('#po-dtl-table').dataTable({
				"sPaginationType" : "two_button",
				"iDisplayLength" : 2,
				"sDom" : '<"pad-it"<"pull-right"f>l>tip>'
			});

			$('#supplier_name').autocomplete({
				serviceUrl : '/supplier/search',
				params : {
					field : 'supplier_name',
					keyword : $(this).val()
				},
				paramName : 'keyword',
				onSelect : function(suggestion) {
					$('#supplier_address').val(suggestion.data.supplier_address);
					$('input[name="po_supplier_id"]').val(suggestion.data.supplier_id);
				},
				transformResult : function(response) {
					response = JSON.parse(response);
					return {
						suggestions : $.map(response, function(dataItem) {
							return {
								value : dataItem.value,
								data : dataItem.data
							};
						})
					};
				}
			});
			
		});
		
		$(document).on('click','a',function(){
			var actionHandle = $(this);
			if(actionHandle.hasClass('edit-po')) {
				changeModal({
					'action':'/po/edit',
					'model':'po',
					'submit_name': 'edit-po',
					'pr_button':'Save Changes',
					'modal_label': 'Edit Purchase Order',
					'run': function(){
						$('#add-to-purchase, .secondary').show();
						var po = actionHandle.parents('td:first').find('input[name="po_id"]').val();
						current_po = po;
						po = cache['po'][po];
						populate({
							'data': cache['po'][po.po_id],
							'name':'po',
							'map': function(v, o) {
									if(v == 'po_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									if(v == 'po_deliv_date') {
										return (new Date(o[v]).toLocaleDateString());
									}
									return o[v];
								}
						});	
					}
				});
			}
			if(actionHandle.hasClass('view-po')){
				changeModal({
					'action':'#',
					'model':'po',
					'submit_name': 'view-po',
					'pr_button':'Back To List',
					'modal_label': 'View Purchase Order',
					'run': function(){
						$('#add-to-purchase').hide();
						$('.secondary').hide();
						
						
						var po = actionHandle.parents('td:first').find('input[name="po_id"]').val();
						po = cache['po'][po];
						populate({
							'data': cache['po'][po.po_id],
							'name':'po',
							'map': function(v, o) {
									if(v == 'po_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									if(v == 'po_deliv_date') {
										return (new Date(o[v]).toLocaleDateString());
									}
									$('#po-modal-form').find('input[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#input[name="'+v+'"]').attr('disabled', 'disabled');
									return o[v];
								}}
						);
						
					}
				});
			}
		});
		
		$('#create-po').click(function(){
			changeModal({
					'action':'#',
					'model':'po',
					'submit_name': 'furnish',
					'pr_button':'Furnish Order',
					'modal_label': 'Add Purchase Order',
					'run': function(){
						$('#add-to-purchase').show();
						current_po = 'new';
						cache['po'][current_po] = {};
						cache['po'][current_po]['po_dtl'] ={};
						clear_form('po', function(){
							$('input[name="po_created"]').val(new Date().toDateString());
						});
					}
				});
		});
		
		$('#add-to-purchase').click(function(){
			changeModal({
					'action':'#',
					'model':'po_dtl',
					'submit_name': 'create-po_dtl',
					'pr_button':'Add To Purchase Order',
					'modal_label': 'Add Item',
					'run': function(){} 
				});
		});
		
		$('#po_dtl-modal-form').submit(function(e){
			e.preventDefault();
			var inputs = $(this).find('input[name]');
			var po_dtl = {};
			$.each(inputs, function(i, o){
				po_dtl[$(o).attr('name')] = $(o).val();
			});
			var row = [];
			row.push(po_dtl_counter+1);
			row.push(po_dtl['po_dtl_item_unit']);
			row.push(po_dtl['po_dtl_item_qty']);
			row.push(po_dtl['po_dtl_item_desc']);
			row.push(po_dtl['po_dtl_item_cost']);
			row.push(po_dtl['po_dtl_item_qty']*po_dtl['po_dtl_item_cost']);
			//TODO: 
			row.push('Action');
			cache['po'][current_po]['po_dtl'][po_dtl_counter]=row;
			poDtlTable.fnAddData(row);
			po_dtl_counter+=1
		});
	})(jQuery);
</script>