<style>
	.po-modal-dialog {
		width: 75%;
	}
	.po .border {
		margin-top: 10px;
	}
	/*.po td {
		text-align: right;
	}*/

	#po-table td:first-child {
		text-align: left;
	}
</style>
<div class="row">
	<div class="col-sm-12">
		<h3>Purchase Order <small>Supplies and materials order to be purchased.</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Purchase Order
			</li>
		</ol>
	</div>
</div>
<div class="form-inline row">
	<div class="col-sm-offset-10 col-sm-2">
		<button type="button" class="btn btn-primary" id="add-to-purchase"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#po-modal">
			Create Order
		</button>
	</div>
</div>
<div class="row border">
	<div class="col-sm-12">
		<div class="table-responsive">
			<table class="table table-hover table-striped table-bordered tablesorter" id="po-table">
				<thead>
					<tr>
						<th>Supplier</th>
						<th>PO No.</th>
						<th>Date</th>
						<th>Procurement Mode</th>
						<th>Total Cost</th>
						<th>Delivery Place</th>
						<th>Delivery Date</th>
						<th>Delivery Term</th>
						<th>Payment Term</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="po-modal" tabindex="-1" role="dialog" 
	aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog po-modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label">
					<span class="modal-form-state">Action Here</span>
				</h4>
			</div>
			<div class="modal-body">
				<form method="post" action="/po/furnish/">
					<div class="border">
						<div class="form-horizontal row">
							<div class="col-sm-7">
								<div class="form-group">
									<label class="col-sm-2 control-label">Supplier</label>
									<div class="col-sm-8">
										<input type="input" class="form-control" placeholder="Name" id="supplier_name">
										<input type="hidden" name="po_supplier_id" >
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Address</label>
									<div class="col-sm-8">
										<input type="input" class="form-control" placeholder="Address" id="supplier_address" disabled>
									</div>
								</div>
							</div>
							<div class="col-sm-5">
								<div class="form-group">
									<label class="col-sm-4 control-label">P.O. No.</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" name="po_no" placeholder="P.O. No.">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Date</label>
									<div class="col-sm-5">
										<input type="text" class="form-control"  value="<?php echo date('F j, Y'); ?>" disabled>
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Mode of Procurement</label>
									<div class="col-sm-5">
										<input type="text" class="form-control" placeholder="Mode" name="po_proc_mod">
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="border">
						<div class="form-horizontal row">
							<div class="col-sm-7">
								<div class="form-group">
									<label class="col-sm-2 control-label">Delivery Place</label>
									<div class="col-sm-4">
										<input type="input" class="form-control" placeholder="Place" name="po_deliv_place">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Delivery Date</label>
									<div class="col-sm-4">
										<input type="date" class="form-control" placeholder="Date" name="po_deliv_date">
									</div>
								</div>
							</div>
							<div class="col-sm-5">
								<div class="form-group">
									<label class="col-sm-4 control-label">Delivery Term</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" placeholder="Term" name="po_deliv_term">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Payment Term</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" placeholder="Term" name="po_pay_term">
									</div>
								</div>
							</div>
						</div>
					</div>
					<hr/>
					<div class="border">
						<div class="row item-input col-sm-12">
							<div class="col-sm-offset-11 col-sm-1">
								<button type="button" class="btn btn-primary intent-add-detail" id="add-to-purchase"
								data-toggle="modal" data-target="#po-dtl-modal" data-backdrop="static" data-keyboard="false">
									Add Item
								</button>
							</div>
						</div>
					</div>
					<div class="row border-space">
						<div class="col-sm-12">
							<h4 align="center">Purchase List</h4>
							<div class="table-responsive">
								<table class="table table-hover table-striped table-bordered tablesorter" id="po-dtl-table">
									<thead>
										<tr>
											<th>Item No.</th>
											<th>Item Unit</th>
											<th>Quantity</th>
											<th>Description</th>
											<th>Unit Cost</th>
											<th>Amount</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody></tbody>
								</table>
							</div>
						</div>
					</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="furnish">
						<span class="modal-form-action">Furnish</span>
					</button>
				</div>
			</form>
			</div>
		</div>
	</div>
</div>

<form class="form-horizontal" id="po-modal-form">
	<div class="modal fade" id="po-dtl-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
				</div>
				<div class="modal-body">
					<div class="form-group ">
						<label for="input-name" class="col-sm-2 control-label">Desc:</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" placeholder="Desc" name="po_dtl[po_dtl_item_desc]" id='po-dtl-desc' required="required">
						</div>
					</div>
					<div class="form-group">
						<label for="input-address" class="col-sm-2 control-label">Unit:</label>
						<div class="col-sm-3">
							<input type="text" class="form-control" id="po-dtl-unit" placeholder="Unit" name="po_dtl[po_dtl_item_unit]" required="required">
						</div>
					</div>
					<div class="form-group">
						<label for="input-tel" class="col-sm-2 control-label">Qty :</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" id="po-dtl-qty" placeholder="QTY" name="po_dtl[po_dtl_item_qty]">
						</div>
					</div>
					<div class="form-group">
						<label for="input-tel" class="col-sm-2 control-label">Cost :</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" placeholder="Unit Cost" id="po-dtl-cost" name="po_dtl[po_dtl_item_cost]">
						</div>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">
							Close
						</button>
						<button type="button" class="btn btn-primary" name="">
							<span class="modal-form-action" >Save changes</span>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/autocomplete.js"></script>
<script type="text/javascript">
	(function($) {
		$('document').ready(function() {
			var actionTemplate = $('#action_tpl')
				.text()
				.trim();
				
			var poTable = $('#po-table').dataTable({
				'sPaginationType' : "two_button",
				"iDisplayLength" : 10,
				"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
				'sAjaxSource': '/po/',
				'sAjaxDataProp': 'data',
				"aoColumns": [
			            { "mData": "supplier_name" },
			            { "mData": "po_no" },
			            { "mData": function(data) {
			            	return (new Date(data.po_created).toDateString());
			            	}},
			            { "mData": "po_proc_mod" },
			            { "mData": "po_total" },
			            { "mData": "po_deliv_place" },
			            { "mData": function(data) {
			            	return (new Date(data.po_deliv_date).toDateString());
			            	}},
			            { "mData": "po_deliv_term" },
			            { "mData": "po_pay_term" },
			            {
			            	'mData': function(data){
			            		var model = new RegExp('//model//','g');
			            		var model_id = new RegExp('/model_id/','g'); 
			            		var target_modal = new RegExp('//target-modal//','g'); 
								var action = actionTemplate
									.replace('\/\/serialize\/\/',JSON.stringify(data))
									.replace(model, 'po')
									.replace(target_modal, 'po-modal')
									.replace(model_id, data.po_id);
			            		return action;
			            	}
			            }]
			});

			poDtlTable = $('#po-dtl-table').dataTable({
				"sPaginationType" : "two_button",
				"iDisplayLength" : 2,
				"sDom" : '<"pad-it"<"pull-right"f>l>tip>'
			});

			$('#supplier_name').autocomplete({
				serviceUrl : '/supplier/search',
				params : {
					field : 'supplier_name',
					keyword : $(this).val()
				},
				paramName : 'keyword',
				onSelect : function(suggestion) {
					$('#supplier_address').val(suggestion.data.supplier_address);
					$('input[name="po_supplier_id"]').val(suggestion.data.supplier_id);
				},
				transformResult : function(response) {
					response = JSON.parse(response);
					return {
						suggestions : $.map(response, function(dataItem) {
							return {
								value : dataItem.value,
								data : dataItem.data
							};
						})
					};
				}
			});
		});
	})(jQuery);
</script>