<style>
	.po-modal-dialog {
		width: 75%;
	}

	.po .border {
		margin-top: 10px;
	}

	#po-table th:first-child {
		width: 20%;
		text-align: left;
	}

	#po-table th:nth-child(2), #po-table th:nth-child(3), #po-table th:nth-child(4) {
		width: 10%;
	}
	#po-table th:last-child {
		width: 5%;
	}

	#po-table td:nth-child(2), #po-table td:nth-child(3), #po-table td:nth-child(4), #po-table td:nth-child(5), #po-table td:nth-child(7), #po-table td:nth-child(8), #po-table td:nth-child(9) {
		text-align: right;
	}

	#po-dtl-table td:nth-child(1) {
		text-align: center;
	}
	#po-dtl-table td:nth-child(2), #po-dtl-table td:nth-child(3), #po-dtl-table td:nth-child(5), #po-dtl-table td:nth-child(6) {
		text-align: right;
	}

	#po_dtl-modal .modal-content {
		margin-top: 30%;
	}

</style>
<div class="row">
	<div class="col-sm-12">
		<h3>Purchase Order <small>Supplies and materials order to be purchased.</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Purchase Order
			</li>
		</ol>
		<?php include(dirname(__FILE__).'\_message.phtml'); ?>
	</div>
</div>
<div class="form-inline row">
	<div class="col-sm-offset-10 col-sm-2">
		<button type="button" class="btn btn-primary" id="create-po"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#po-modal">
			Create
		</button>
	</div>
</div>
<div class="row border">
	<div class="col-sm-12">
		<div class="table-responsive">
			<table class="table table-hover table-striped table-bordered tablesorter" id="po-table">
				<thead>
					<tr>
						<th>Supplier</th>
						<th>PO No.</th>
						<th>Date</th>
						<th>Procurement Mode</th>
						<th>Total Cost</th>
						<th>Delivery Place</th>
						<th>Delivery Date</th>
						<th>Delivery Term</th>
						<th>Payment Term</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="po-modal" tabindex="-1" role="dialog" 
	aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog po-modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label">
					<span class="modal-form-state">Action Here</span>
				</h4>
			</div>
			<div class="modal-body">
				<form method="post" action="/po/furnish/" id="po-modal-form">
					<input type="hidden" name="po_id"/>
					<div class="border">
						<div class="form-horizontal row">
							<div class="col-sm-7">
								<div class="form-group">
									<label class="col-sm-2 control-label">Supplier</label>
									<div class="col-sm-10">
										<input type="input" class="form-control" placeholder="Name" id="supplier_name">
										<input type="hidden" name="po_supplier_id" >
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Address</label>
									<div class="col-sm-10">
										<input type="input" class="form-control" placeholder="Address" id="supplier_address" disabled>
									</div>
								</div>
							</div>
							<div class="col-sm-5">
								<div class="form-group">
									<label class="col-sm-4 control-label">P.O. No.</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" name="po_no" placeholder="P.O. No.">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Date</label>
									<div class="col-sm-6">
										<div class='input-group date po-created'>
											<input type='text' name="po_created" class="form-control" />
											<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
											</span>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Mode of Procurement</label>
									<div class="col-sm-5">
										<input type="text" class="form-control" placeholder="Mode" name="po_proc_mod">
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="border">
						<div class="form-horizontal row">
							<div class="col-sm-7">
								<div class="form-group">
									<label class="col-sm-2 control-label">Delivery Place</label>
									<div class="col-sm-4">
										<input type="input" class="form-control" placeholder="Place" name="po_deliv_place">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-2 control-label">Delivery Date</label>
									<div class="col-sm-4">
										<div class='input-group date deliv-date'>
											<input type='text' name="po_deliv_date" class="form-control" />
											<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
											</span>
										</div>
									</div>
								</div>
							</div>
							<div class="col-sm-5">
								<div class="form-group">
									<label class="col-sm-4 control-label">Delivery Term</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" placeholder="Term" name="po_deliv_term">
									</div>
								</div>
								<div class="form-group">
									<label class="col-sm-4 control-label">Payment Term</label>
									<div class="col-sm-4">
										<input type="text" class="form-control" placeholder="Term" name="po_pay_term">
									</div>
								</div>
							</div>
						</div>
					</div>
					<hr/>
					<div class="border">
						<div class="row item-input col-sm-12">
							<div class="col-sm-offset-11 col-sm-1">
								<button type="button" class="btn btn-primary" id="add-to-purchase"
								data-toggle="modal" data-target="#po_dtl-modal" data-backdrop="static" data-keyboard="false">
									Add Item
								</button>
							</div>
						</div>
					</div>
					<div class="row border-space">
						<div class="col-sm-12">
							<h4 align="center">Purchase List</h4>
							<div class="table-responsive">
								<table class="table table-hover table-striped table-bordered tablesorter" id="po-dtl-table">
									<thead>
										<tr>
											<th>Item No.</th>
											<th>Item Unit</th>
											<th>Quantity</th>
											<th>Description</th>
											<th>Unit Cost</th>
											<th>Amount</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody></tbody>
								</table>
							</div>
						</div>
					</div>
					<div id="hidden_data"></div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default secondary" data-dismiss="modal">
							Close
						</button>
						<button type="submit" class="btn btn-primary" name="furnish">
							<span class="modal-form-action">Furnish</span>
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="po_dtl-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
			</div>
			<div class="modal-body">
				<form id="po_dtl-modal-form" action='#'>
				<div class="row border">
							<div class="border">
								<div class="col-sm-12">
									<label for="input-name" class="col-sm-2 control-label">Desc</label>
									<div class="form-group col-sm-10">	
										<input type="text" class="form-control" placeholder="Desc"
											name="po_dtl_item_desc" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-address" class="col-sm-2 control-label">Unit</label>
									<div class="form-group col-sm-3">
										<input type="text" class="form-control" placeholder="Unit"
											name="po_dtl_item_unit" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-tel" class="col-sm-2 control-label">Qty</label>
									<div class="form-group col-sm-3">
										<input type="text" class="form-control" placeholder="QTY"
											name="po_dtl_item_qty" required="required">
									</div>
								</div>
								<div class="col-sm-12">
									<label for="input-tel" class="col-sm-2 control-label">Cost</label>
									<div class="form-group col-sm-3" required="required">
										<input type="text" class="form-control" placeholder="Unit Cost" name="po_dtl_item_cost">
									</div>
								</div>
							</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default secondary" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="">
						<span class="modal-form-action" >Save changes</span>
					</button>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/autocomplete.js"></script>
<script type="text/javascript" src="/assets/js/modal_control.js"></script>
<script type="text/javascript">
	(function($) {
		current_po = 'new';
		current_po_dtl = null;
		current_po_dtl_row = null;
		po_detail_table = {};
		po_table = {};
		action_template = $('#action_tpl').text().trim();
		
		$('document').ready(function() {
			$('.po-created').datetimepicker({});
			
			$('.deliv-date').datetimepicker({
				pickTime: false
			});
			
			//PO INIT
			po_table = $('#po-table').dataTable({
				'sPaginationType' : "two_button",
				"iDisplayLength" : 10,
				"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
				'sAjaxSource': '/po/',
				'sAjaxDataProp': 'data',
				"aoColumns": [
			            { "mData": "supplier_name" },
			            { "mData": "po_no" },
			            { "mData": function(data) {
			            	return moment(data.po_created).format('ddd, MMM Do YYYY');
			       		}},
			            { "mData": "po_proc_mod" },
			            { "mData": function(data){
			            		return parseFloat(data['po_total']).moneyFormat();
			            }},
			            { "mData": "po_deliv_place" },
			            { "mData": function(data) {
			            	return moment(data.po_deliv_date).format('ddd, MMM Do YYYY');
			            	}},
			            { "mData": "po_deliv_term" },
			            { "mData": "po_pay_term" },
			            {
			            	'mData': function(data){
			            		var model = new RegExp('//model//','g');
			            		var model_id = new RegExp('/model_id/','g'); 
			            		var target_modal = new RegExp('//target-modal//','g'); 
								var action = action_template
									.replace(model, 'po')
									.replace(target_modal, 'po')
									.replace(model_id, data.po_id);
			            		return action;
			            	}
			            }],
				"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
				  oSettings.jqXHR = $.ajax( {
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": {po:'all'},
					"success": fnCallback
				  } );
				}
			});
			
			//PO DETAIL INIT
			po_detail_table = $('#po-dtl-table').dataTable({
				"sPaginationType" : "two_button",
				"iDisplayLength" : 3,
				"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
				"bAutoWidth": false
			});
			
			//AUTOCOMPLETE
			$('#supplier_name').autocomplete({
				serviceUrl : '/supplier/search',
				params : {
					field : 'supplier_name',
					keyword : $(this).val()
				},
				paramName : 'keyword',
				onSelect : function(suggestion) {
					$('#supplier_address').val(suggestion.data.supplier_address);
					$('input[name="po_supplier_id"]').val(suggestion.data.supplier_id);
				},
				transformResult : function(response) {
					response = JSON.parse(response);
					return {
						suggestions : $.map(response, function(dataItem) {
							return {
								value : dataItem.value,
								data : dataItem.data
							};
						})
					};
				}
			});
			
		});
		
		$(document).on('click','a',function(){
			var action_handle = $(this);
			var row = action_handle.parents('tr:first');
			var po_id;
			//EDIT PO
			if(action_handle.hasClass('edit-po')) {
				po_detail_table.fnClearTable();
				var row_position = po_table.fnGetPosition(row[0]); 
				var row_data = po_table.fnGetData(row[0]);
				current_po = row_data;
				current_po_row = row_position;
				changeModal({
					'action':'/po/edit',
					'model':'po',
					'submit_name': 'edit-po',
					'pr_button':'Save Changes',
					'modal_label': 'Edit Purchase Order',
					'run': function(){
						$('#add-to-purchase, .secondary').show();
						populate({
							'data': current_po,
							'name':'po',
							'map': function(v, o) {
									if(v == 'po_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									if(v == 'po_deliv_date') {
										return (new Date(o[v]).toLocaleDateString());
									}
									return o[v];
								}
						}, function() {
							po_detail_table = $('#po-dtl-table').dataTable({
								"sPaginationType" : "two_button",
								"iDisplayLength" : 3,
								"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
								'sAjaxSource': '/po/',
								'sAjaxDataProp': 'data',
								"bDestroy" : true,
								"bAutoWidth": false,
								"aoColumns": [
							            { "mData": "po_dtl_item_no" },
							            { "mData": "po_dtl_item_unit" },
							            { "mData": "po_dtl_item_qty" },
							            { "mData": "po_dtl_item_desc" },
							            { "mData": function(data){ 
							            	return parseFloat(data['po_dtl_item_cost']).moneyFormat();
							            }},
							            { "mData": function(data) {
							            	var amount = parseFloat(data.po_dtl_item_qty*data.po_dtl_item_cost);
											return amount.moneyFormat();
							            }},
							            { 
											'mData': function(data){
												var model = new RegExp('//model//','g');
												var model_id = new RegExp('/model_id/','g'); 
												var target_modal = new RegExp('//target-modal//','g'); 
												
												var action = action_template
													.replace(model, 'po_dtl')
													.replace(target_modal, 'po_dtl')
													.replace(model_id, data.po_dtl_id);
												return action;
											}
										},
							            ],
								"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
								  oSettings.jqXHR = $.ajax( {
									"dataType": 'json',
									"type": "POST",
									"url": sSource,
									"data": {po:current_po['po_id']},
									"success": fnCallback
								  } );
								}
							});
						});	
					}
				});
			}
			//VIEW PO
			if(action_handle.hasClass('view-po')) {
				var row_position = po_table.fnGetPosition(row[0]); 
				var row_data = po_table.fnGetData(row[0]);
				current_po = row_data;
				current_po_row = row_position;
				changeModal({
					'action':'/po',
					'model':'po',
					'submit_name': 'view-po',
					'pr_button':'Back To List',
					'modal_label': 'View Purchase Order',
					'run': function(){
						$('#add-to-purchase').hide();
						$('.secondary').hide();
						
						populate({
							'data': current_po,
							'name':'po',
							'map': function(v, o) {
									if(v == 'po_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									if(v == 'po_deliv_date') {
										return (new Date(o[v]).toLocaleDateString());
									}									
									return o[v];
						}}, function(){
								$.each(Object.keys(current_po), function(i, v){
									$('#po-modal-form').find('input[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#'+v)
										.attr('disabled', 'disabled');
								});
								po_detail_table = $('#po-dtl-table').dataTable({
										"sPaginationType" : "two_button",
										"iDisplayLength" : 3,
										"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
										'sAjaxSource': '/po/',
										'sAjaxDataProp': 'data',
										"bDestroy" : true,
										"bAutoWidth": false,
										"aoColumns": [
												{ "mData": "po_dtl_item_no" },
												{ "mData": "po_dtl_item_unit" },
												{ "mData": "po_dtl_item_qty" },
												{ "mData": "po_dtl_item_desc" },
												{ "mData": function(data){ 
									            	return parseFloat(data['po_dtl_item_cost']).formatMoney(2,',','.');
									            }},
									            { "mData": function(data) {
									            	var amount = parseFloat(data.po_dtl_item_qty*data.po_dtl_item_cost);
													return amount.formatMoney(2,',','.');
									            }},
												{ 'mData': function(data) {return " ";}},
											],
										"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
										  oSettings.jqXHR = $.ajax( {
											"dataType": 'json',
											"type": "POST",
											"url": sSource,
											"data": {po:current_po['po_id']},
											"success": fnCallback
										  } );
										}
									});
						});
					}
				});
			}
			//IF EDITING DETAIL
			if(action_handle.hasClass('edit-po_dtl')) {
				var row_position = po_detail_table.fnGetPosition(row[0]); 
				var row_data = po_detail_table.fnGetData(row[0]);
				current_po_dtl = row_data;
				current_po_dtl_row = row_position;
				
				//MODIFY MODAL FOR EDIT MODE
				changeModal({
					'action':'/po/#',
					'model':'po_dtl',
					'submit_name': 'edit-po_dtl',
					'pr_button':'Save Changes',
					'modal_label': 'Edit Item',
					'run': function() {
						
						//POPULATE TO THE FORM
						populate({
							'data': row_data,
							'name':'po_dtl',
							'map': function(v, o) {
									if(v == 'po_dtl_item_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									return o[v];
								}}
						);
						
					}
				});
			}
			//IF VIEWING DETAIL
			if(action_handle.hasClass('view-po_dtl')) {
				var row_position = po_detail_table.fnGetPosition(row[0]); 
				var row_data = po_detail_table.fnGetData(row[0]);
				current_po_dtl = row_data;
				current_po_dtl_row = row_position;
				changeModal({
					'action':'#',
					'model':'po_dtl',
					'submit_name': 'view-po_dtl',
					'pr_button':'Back to Order',
					'modal_label': 'View Item',
					'run': function() {
						populate({
							'data': current_po_dtl,
							'name':'po_dtl',
							'map': function(v, o) {
									if(v == 'po_dtl_item_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									return o[v];
							}}, function(){
								$('#po_dtl-modal-form .secondary').hide();
								$('#po_dtl-modal-form').find('input').attr('disabled','disabled');
							}
						);
						
						
					}
				});
			}
		});
		
		//CREATE PO
		$('#create-po').click(function(){
			po_detail_table.fnClearTable();
			changeModal({
					'action':'/po/furnish',
					'model':'po',
					'submit_name': 'furnish',
					'pr_button':'Furnish Order',
					'modal_label': 'Create Purchase Order',
					'run': function(){
						$('#add-to-purchase').show();
						clear_form('po', function(){
							$('input[name="po_created"]').val(new Date().toDateString());
						});
						po_detail_table = $('#po-dtl-table').dataTable({
								"sPaginationType" : "two_button",
								"iDisplayLength" : 3,
								"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
								"bDestroy" : true,
								"bAutoWidth": false,
								"aoColumns": [
							            { "mData": "po_dtl_item_no" },
							            { "mData": "po_dtl_item_unit" },
							            { "mData": "po_dtl_item_qty" },
							            { "mData": "po_dtl_item_desc" },
							            { "mData": function(data) {
							            		return parseFloat(data["po_dtl_item_cost"]).moneyFormat();
							            } },
							            { "mData": function(data) {
							            	var amount = data.po_dtl_item_qty*data.po_dtl_item_cost;
											return parseFloat(amount).moneyFormat();
							            }},
							            { 'mData': function(data){
												var model = new RegExp('//model//','g');
												var model_id = new RegExp('/model_id/','g'); 
												var target_modal = new RegExp('//target-modal//','g'); 
												
												var action = action_template
													.replace(model, 'po_dtl')
													.replace(target_modal, 'po_dtl')
													.replace(model_id, data.po_dtl_id);
												return action;
											}
										},
									]
								});
					}
				});
		});
		
		//ADD ITEM
		$('#add-to-purchase').click(function(){
			changeModal({
					'action':'#',
					'model':'po_dtl',
					'submit_name': 'create-po_dtl',
					'pr_button':'Add To Purchase Order',
					'modal_label': 'Add Item',
					'run': function(){
						clear_form('po_dtl');
					} 
				});
		});
		
		//HEADER SUBMIT HANDLER
		$('#po-modal-form').submit(function(e){
			//e.preventDefault();
			$('#hidden_data').html('');
			var data = po_detail_table.fnGetData();
			var hidden_aggregation = $('#hidden_data');
			$.each(data, function(index, o){
				Object.keys(o).forEach(function(v,i,a){
					hidden_aggregation.append(
						'<input type="hidden" name="po_dtl['+index+']['+v+']" value="'+o[v]+'"/>');
					});
			});
		});
				
		//DETAIL SUBMIT HANDLER
		$('#po_dtl-modal-form').submit(function(e){
			var form = $(this);
			var button_action = form.find('.btn-primary').attr('name');
			e.preventDefault();
			
			var inputs = form.find('input[name]');
												
			switch(button_action){
				case 'edit-po_dtl':	
					$.each(inputs, function(i, o) {
						if (current_po_dtl[$(o).attr('name')]!= 'undefined') {
							current_po_dtl[$(o).attr('name')] = $(o).val();
						}
					});
					po_detail_table.fnUpdate(current_po_dtl, current_po_dtl_row);
					break;
				case 'create-po_dtl':
					current_po_dtl = {};
					$.each(inputs, function(i, o) {
						current_po_dtl[$(o).attr('name')] = $(o).val();
					});
					current_po_dtl['po_dtl_item_no'] = po_detail_table.fnGetData().length+1; 
					current_po_dtl['po_dtl_item_created'] = (new Date()).toLocaleString();
					po_detail_table.fnAddData(current_po_dtl);
					break;
				default:
					break;
			};
			$('#po_dtl-modal').modal('hide');
			$('#po_dtl-modal-form').find('input').removeAttr('disabled');
		});
	})(jQuery);
</script>