<style>
	.rm-modal-dialog {
		width: 75%;
	}

	.rm .border {
		margin-top: 10px;
	}

	#rm-table th:first-child {
		width: 20%;
		text-align: left;
	}

	#rm-table th:nth-child(2), #rm-table th:nth-child(3), #rm-table th:nth-child(4) {
		width: 10%;
	}
	#rm-table th:last-child {
		width: 5%;
	}

	#rm-table td:nth-child(4), #rm-table td:nth-child(5) {
		text-align: right;
	}

	#rm-dtl-table td:nth-child(1) {
		text-align: center;
	}
	#rm-dtl-table td:nth-child(2), #rm-dtl-table td:nth-child(3), #rm-dtl-table td:nth-child(5), #rm-dtl-table td:nth-child(6) {
		text-align: right;
	}

	#rm_dtl-modal .modal-content {
		margin-top: 30%;
	}
	
	
	.dataTables_filter label{
		width:250px;
	}
	[name="rm-table_length"],[name="rm-dtl-table_length"]{
		display: inline;
		width: 100px;
		height: 34px;
		padding: 6px 12px;
		font-size: 14px;
		line-height: 1.428571429;
		color: #555555;
		vertical-align: middle;
		background-color: #ffffff;
		background-image: none;
		border: 1px solid #cccccc;
		border-radius: 4px;
	}
	
	
	.modal-body{
		max-height:450px;
		overflow-y:auto;
	}
</style>
<div class="row-fluid">
	<div class="col-lg-12">
		<h3>Returned Materials <small>Returned of excess materials</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Returned Materials
			</li>
		</ol>
		<?php include(dirname(__FILE__).'\_message.phtml'); ?>
	</div>
</div><!-- /.row -->
<div class="row-fluid">
	<div class="col-xs-12">
		<button type="button" class="btn btn-primary pull-right" id="create-rm"
			data-backdrop="static" data-keyboard="false"
				data-toggle="modal" data-target="#rm-modal">
			Create
		</button>
	</div>
</div>
<div class="row-fluid border">
	<div class="col-sm-12" style="padding-top:20px">
		<div class="table-responsive">
			<table class="table table-hover table-striped table-bordered tablesorter" id="rm-table">
				<thead>
					<tr>
						<th>Division</th>
						<th>Office</th>
						<th>Responsibility Code</th>
						<th>RM No</th>
						<th>Date</th>
						<th>Purpose</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</div>
<form method="post" action="/rm/furnish/" id="rm-modal-form">
	<div class="modal fade" id="rm-modal" tabindex="-1" role="dialog" 
		aria-labelledby="mymodallabel" aria-hidden="true">
		<div class="modal-dialog rm-modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="my-modal-label">
						<span class="modal-form-state">Action Here</span>
					</h4>
				</div>
				<div class="modal-body">
						<input type="hidden" name="rm_id"/>
						<div class="border">
							<div class="form-horizontal row-fluid">
								<div class="col-sm-4">
									<div class="form-group">
										<label class="col-sm-4 control-label">Issuance No.</label>
										<div class="col-sm-6">
											<input type="text" class="form-control" id="issuance_no" placeholder="Issuance No."/>
											<input type="hidden" name="issuance_id"/>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-4 control-label">Division</label>
										<div class="col-sm-6">
											<input type="input" class="form-control" placeholder="Division" name="rm_division"/>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-4 control-label">Office</label>
										<div class="col-sm-6">
											<input type="input" class="form-control" placeholder="Office" name="rm_office"/>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-4 control-label">Returned:</label>
										<div class="col-sm-6">
											<input type="input" class="form-control" placeholder="Returned" name="rm_returned"/>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-4 control-label">Approved:</label>
										<div class="col-sm-6">
											<input type="input" class="form-control" placeholder="Approval" name="rm_approved"/>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-4 control-label">Received:</label>
										<div class="col-sm-6">
											<input type="input" class="form-control" placeholder="Receiver" name="rm_received"/>
										</div>
									</div>
								</div>
								<div class="col-sm-8">
									<div class="form-group">
										<label class="col-sm-6 control-label">RM No.</label>
										<div class="col-sm-5">
											<input type="text" class="form-control" name="issuance_no" placeholder="RM No."/>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-6 control-label">Responsibility Center Code</label>
										<div class="col-sm-5">
											<input type="text" class="form-control" name="rm_rcc" placeholder="RCC">
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-6 control-label">RM Date</label>
										<div class="col-sm-5">
											<input type="text" class="form-control" name="rm_created" placeholder="RM Date">
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-6 control-label">Purpose</label>
										<div class="col-sm-5">
											<input type="text" class="form-control" name="rm_purpose" placeholder="Purpose">
										</div>
									</div>
								</div>																
							</div>

						</div>
						<hr/>
						<div class="row-fluid border-space">
							<div class="col-sm-12">
								<h4 align="center">List</h4>
								<div class="table-responsive">
									<table class="table table-hover table-striped table-bordered tablesorter" id="rm-dtl-table">
										<thead>
											<tr>
												<th>Item No</th>
												<th>Acct No</th>
												<th>Stock No</th>
												<th>Unit</th>
												<th>Description</th>
												<th>Size</th>
												<th>Qty</th>
												<th>Issued Qty</th>
												<th>Returned Qty</th>
												<th>Remarks</th>
												<th>Action</th>
											</tr>
										</thead>
										<tbody></tbody>
									</table>
								</div>
							</div>
						</div>
						<div id="hidden_data"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default secondary" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="furnish">
						<span class="modal-form-action">Furnish</span>
					</button>
				</div>		
			</div>
		</div>
	</div>
</form>
<form id="rm_dtl-modal-form" action='#'>		
<div class="modal fade" id="rm_dtl-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
			</div>
			<div class="modal-body">
				<div class="row border">
					<div class="border">
						<div class="col-sm-12">
							<label for="input-name" class="col-sm-3 control-label">Stock No</label>
							<div class="form-group col-sm-5">	
								<input type="text" class="form-control" placeholder="Stock No"
									name="rm_dtl_item_stock_no" disabled="disabled">
							</div>
						</div>
						<div class="col-sm-12">
							<label for="input-address" class="col-sm-3 control-label">Desc</label>
							<div class="form-group col-sm-9">
								<input type="text" class="form-control" placeholder="Description"
									name="rm_dtl_item_desc" disabled="disabled">
							</div>
						</div>
						<div class="col-sm-12">
							<label for="input-address" class="col-sm-3 control-label">Size</label>
							<div class="form-group col-sm-5">
								<input type="text" class="form-control" placeholder="Size"
									name="rm_dtl_item_size" disabled="disabled">
							</div>
						</div>
						<div class="col-sm-12">
							<label for="input-address" class="col-sm-3 control-label">Unit</label>
							<div class="form-group col-sm-2">
								<input type="text" class="form-control" placeholder="UNIT"
									name="rm_dtl_item_unit" disabled="disabled">
							</div>
						</div>
						<div class="col-sm-12">
							<label for="input-tel" class="col-sm-3 control-label">Issued Qty</label>
							<div class="form-group col-sm-2">
								<input type="text" class="form-control" placeholder="QTY"
									name="issuance_dtl_item_issued" required="required">
							</div>
						</div>
						<div class="col-sm-12">
							<label for="input-name" class="col-sm-3 control-label">Returned Qty</label>
							<div class="form-group col-sm-5">	
								<input type="text" class="form-control" placeholder="QTY"
									name="issuance_dtl_item_issued" >
							</div>
						</div>
						<div class="col-sm-12">
							<label for="input-tel" class="col-sm-3 control-label">Remarks</label>
							<div class="form-group col-sm-5">
								<input type="text" class="form-control" placeholder="Remarks:"
									name="rm_dtl_remarks" >
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default secondary" data-dismiss="modal">
						Close
					</button>
					<button type="submit" class="btn btn-primary" name="">
						<span class="modal-form-action" >Save changes</span>
					</button>
				</div>
			</div>
		</div>
	</div>
</div>
</form>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/autocomplete.js"></script>
<script type="text/javascript" src="/assets/js/modal_control.js"></script>
<script type="text/javascript">
	(function($) {
		current_rm = 'new';
		current_rm_dtl = null;
		current_rm_dtl_row = null;
		rm_dtl_table = {};
		rm_table = {};
		action_template = $('#action_tpl').text().trim();
		rm_columns = [{ "mData": "ris_division" },
			            { "mData": "ris_office" },
			            { "mData": 'ris_rcc' },
			            { "mData": "ris_no" },
			            { "mData": function(data) {
			            	return moment(data.rm_created).format('ddd, MMM Do YYYY');
			            }},
			            { "mData": "ris_purpose" },
			            {
			            	'mData': function(data) {
								console.log(data);
			            		var model = new RegExp('//model//','g');
			            		var model_id = new RegExp('/model_id/','g'); 
			            		var target_modal = new RegExp('//target-modal//','g'); 
								var action = action_template
									.replace(model, 'rm')
									.replace(target_modal, 'rm')
									.replace(model_id, data.rm_id);
								action = $(action).clone();
			            		var li = $(action).find('a.delete-rm').parent();
								li.find('a').remove();
								li = $(action).find('a.edit-rm').parent();
								li.find('a').remove();
								action.find('ul.dropdown-menu').append(
								'<li><a class="print_report-rm" href="/rm/report/'+data.rm_id+
									'" target="_blank" title="Print from pdf file."'+
									' onclick="return confirm('+"'"+
									'Do you want to print a report to a pdf file?'+"'"+
									')">Print</a></li>');
								if(!parseInt(data.rm_is_cancelled) &&
									(!parseInt(data.rm_is_issued) && !parseInt(data.rm_is_cancelled)) &&
										!parseInt(data.rm_is_issued)
									) {
									li.append('<a href="/rm/cancel/'+data.rm_id+'" class="cancel-rm"'+
									'onclick="return confirm('+"'"+
									'Do you really want to cancel Issuance no.'+
									data.issuance_no+"'"+')">Cancel</a>');
								}
								action = action.html();
			            		return action;
			            	}
			            }];
		
		rm_dtl_columns = [{ "mData": function(data) {
				console.log(data);
				return data.ris_dtl_item_no;
			}},
			{ "mData": "ris_dtl_item_acct_no" },
			{ "mData": function(data){
				if(data.ris_dtl_item_stock_no){
					return data.ris_dtl_item_stock_no;
				}
				return "";
			}},
			{ "mData": "ris_dtl_item_unit" },
			{ "mData": "ris_dtl_item_desc" },
			{ "mData": "ris_dtl_item_size" },
			{ "mData": "ris_dtl_item_qty" },
			{ "mData": function(data) {
				return (data.issuance_dtl_item_issued)?data.issuance_dtl_item_issued:'';
				}
			},
			{ "mData": function(data){
				return (data.ris_dtl_item_charging)?data.ris_dtl_item_charging:'';
				}
			},
			{ "mData": function(data){
				return (data.ris_dtl_remarks)?data.ris_dtl_remarks:'';
				}
			},
			{'mData': function(data) {
					var model = new RegExp('//model//','g');
					var model_id = new RegExp('/model_id/','g'); 
					var target_modal = new RegExp('//target-modal//','g'); 
					
					var action = action_template
						.replace(model, 'ris_dtl')
						.replace(target_modal, 'ris_dtl')
						.replace(model_id, data.ris_dtl_id);
					
					
					action = $(action).clone();
					$(action). find('a.edit-ris_dtl').text('Return Item');
					$(action).find('a.delete-ris_dtl').attr('href', '#').removeAttr('onclick');
					action = $(action).html();
					return action;
				}
			},
		];
		
		console.log(rm_dtl_columns.length);
		
		$('document').ready(function() {
			$('.rm-created').datetimepicker({});
			
			$('.deliv-date').datetimepicker({
				pickTime: false
			});
			
			//rm INIT
			rm_table = $('#rm-table').dataTable({
				'sPaginationType' : "two_button",
				"iDisplayLength" : 10,
				"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
				'sAjaxSource': '/rm/',
				'sAjaxDataProp': 'data',
				"aoColumns": rm_columns,
				"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
					console.log(aoData);
					
				  oSettings.jqXHR = $.ajax( {
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": {returned:'all'},
					"success": fnCallback
				  });
				}
			});
			
			//rm DETAIL INIT
			rm_dtl_table = $('#rm-dtl-table').dataTable({
				"sPaginationType" : "two_button",
				"iDisplayLength" : 3,
				"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
				"bAutoWidth": false
			});
			
			//rm POPULATION
			$('#issuance_no').on('blur', function(){
				var input = $(this);
				var issuance_number = input.val();
				
				clear_form('rm', function(){
					$('input[name="rm_created"]').val(moment().format('M/D/YYYY'));
				});
				
				$.post ('/rm/', {issuance_no : issuance_number}, function(data){
					
					rm = (data.data)?data.data:false;
					/*
					if(!rm.rm_dtl.length) {
						//alert('Issuance Number '+issuance_no+' not existing!');
						input.empty().focus();
					}*/
					console.log(rm);
					if(rm){
						rm.rm_is_issued = parseInt(rm.rm_is_issued); 
						rm.rm_is_cancelled = parseInt(rm.rm_is_cancelled); 
						if(rm.rm_is_issued){
							alert('Requisition Order '+rm.rm_no+' is already issued or cancelled!');
							input.empty().focus();
						}
						if(!rm.rm_is_issued && !rm.rm_is_cancelled){
							populate({
								name:'rm',
								data: rm,
								map: function(v,o){ 
									if(v == 'rm_created') {
										return moment(v[o]).format('M/D/YYYY');
									}
									return o[v];
								}
							}, function(){
									rm_dtl_table = $('#rm-dtl-table').dataTable({
											'sPaginationType' : "two_button",
											"iDisplayLength" : 10,
											"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
											"aoColumns": rm_dtl_columns,
											"aaData" : rm.rm_dtl,
											"bDestroy" : true,
											"bAutoWidth": false
									});
							
							});
							
							
						}
					}
				});
			});
			
		});
		
		//ACTION HANDLER
		$(document).on('click','a',function(){
			var action_handle = $(this);
			var row = action_handle.parents('tr:first');
			var rm_id;
			//EDIT rm
			if(action_handle.hasClass('edit-rm')) {
				rm_dtl_table.fnClearTable();
				var row_position = rm_table.fnGetPosition(row[0]); 
				var row_data = rm_table.fnGetData(row[0]);
				current_rm = row_data;
				current_rm_row = row_position;
				changeModal({
					'action':'/requisition/edit',
					'model':'rm',
					'submit_name': 'edit-rm',
					'pr_button':'Save Changes',
					'modal_label': 'Edit Requisition',
					'run': function() {
						$('.secondary').show();
						populate({
							'data': current_rm,
							'name':'rm',
							'map': function(v, o) {
									if(v == 'rm_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									if(v == 'rm_deliv_date') {
										return (new Date(o[v]).toLocaleDateString());
									}
									return o[v];
								}
						}, function() {
							console.log(current_rm);
							rm_dtl_table = $('#rm-dtl-table').dataTable({
								"sPaginationType" : "two_button",
								"iDisplayLength" : 3,
								"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
								'sAjaxSource': '/requisition/',
								'sAjaxDataProp': 'data',
								"bDestroy" : true,
								"bAutoWidth": false,
								"aoColumns": rm_dtl_columns,
								"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
								  oSettings.jqXHR = $.ajax( {
									"dataType": 'json',
									"type": "POST",
									"url": sSource,
									"data": {rm:current_rm['rm_id']},
									"success": fnCallback
								  } );
								}
							});
						});	
					}
				});
			}
			//VIEW rm
			if(action_handle.hasClass('view-rm')) {
				var row_position = rm_table.fnGetPosition(row[0]); 
				var row_data = rm_table.fnGetData(row[0]);
				current_rm = row_data;
				current_rm_row = row_position;
				changeModal({
					'action':'/issuance',
					'model':'rm',
					'submit_name': 'view-rm',
					'pr_button':'Back To List',
					'modal_label': 'View Issuance',
					'run': function(){
						$('#add-to-purchase').hide();
						$('.secondary').hide();
						
						populate({
							'data': current_rm,
							'name':'rm',
							'map': function(v, o) {
									if(v == 'rm_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									if(v == 'rm_deliv_date') {
										return (new Date(o[v]).toLocaleDateString());
									}									
									return o[v];
						}}, function() {
								console.log(current_rm, '<- current rm');
								$.each(Object.keys(current_rm), function(i, v){
									$('#rm-modal-form').find('input[name="'+v+'"]')
										.attr('disabled', 'disabled');
									$('#'+v)
										.attr('disabled', 'disabled');
								});
								rm_dtl_table = $('#rm-dtl-table').dataTable({
										"sPaginationType" : "two_button",
										"iDisplayLength" : 3,
										"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
										'sAjaxSource': '/issuance/',
										'sAjaxDataProp': 'data',
										"bDestroy" : true,
										"bAutoWidth": false,
										"aoColumns": rm_dtl_columns,
										"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
										  oSettings.jqXHR = $.ajax( {
											"dataType": 'json',
											"type": "POST",
											"url": sSource,
											"data": {issuance_no:current_rm['issuance_no']},
											"success": fnCallback
										  } );
										}
									});
						});
						bVis = rm_dtl_table.fnSettings().aoColumns[7].bVisible;
						rm_dtl_table.fnSetColumnVis( 7, bVis ? false : true );
						
					}
				});
			}
			//IF EDITING DETAIL
			if(action_handle.hasClass('edit-rm_dtl')) {
				var row_position = rm_dtl_table.fnGetPosition(row[0]); 
				var row_data = rm_dtl_table.fnGetData(row[0]);
				current_rm_dtl = row_data;
				current_rm_dtl_row = row_position;
				
				//MODIFY MODAL FOR EDIT MODE
				changeModal({
					'action':'/rm/#',
					'model':'rm_dtl',
					'submit_name': 'edit-rm_dtl',
					'pr_button':'Save Changes',
					'modal_label': 'Issue Requested Item',
					'run': function() {
						
						//populate TO THE FORM
						populate({
							'data': row_data,
							'name':'rm_dtl',
							'map': function(v, o) {
									if(v == 'rm_dtl_item_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									return o[v];
								}}
						);
						
					}
				});
			}
			//IF VIEWING DETAIL
			if(action_handle.hasClass('view-rm_dtl')) {
				var row_position = rm_dtl_table.fnGetPosition(row[0]); 
				var row_data = rm_dtl_table.fnGetData(row[0]);
				current_rm_dtl = row_data;
				current_rm_dtl_row = row_position;
				changeModal({
					'action':'#',
					'model':'rm_dtl',
					'submit_name': 'view-rm_dtl',
					'pr_button':'Back to Order',
					'modal_label': 'View Item',
					'run': function() {
						populate({
							'data': current_rm_dtl,
							'name':'rm_dtl',
							'map': function(v, o) {
									if(v == 'rm_dtl_item_created') {
										var dateIs = new Date(o[v].split(' ')[0]).toDateString();
										return dateIs;
									}
									return o[v];
							}}, function(){
								$('#rm_dtl-modal-form .secondary').hide();
								$('#rm_dtl-modal-form').find('input').attr('disabled','disabled');
							}
						);
						
						
					}
				});
			}
			
			//DELETING DETAIL
			if(action_handle.hasClass('delete-rm_dtl')) {
				var row_position = rm_dtl_table.fnGetPosition(row[0]); 
				var row_data = rm_dtl_table.fnGetData(row[0]);
				current_rm_dtl = row_data;
				current_rm_dtl_row = row_position;
				if(confirm(
					'Are you sure you want to delete this??'
				)){
					rm_dtl_table.fnDeleteRow(current_rm_dtl_row);
					rm_dtl_table.fnDraw();
				}				
			}
		});
		
		//CREATE rm
		$('#create-rm').click(function(){
			//rm_dtl_table.fnClearTable();
			changeModal({
					'action':'/rm/furnish',
					'model':'rm',
					'submit_name': 'furnish',
					'pr_button':'Furnish RM',
					'modal_label': 'Return Item',
					'run': function(){
						$('#add-to-purchase').show();
						clear_form('rm', function(){
							$('input[name="rm_created"]').val(new Date().toDateString());
						});
						rm_dtl_table = $('#rm-dtl-table').dataTable({
								"sPaginationType" : "two_button",
								"iDisplayLength" : 3,
								"sDom" : '<"pad-it"<"pull-right"f>l>tip>',
								"bDestroy" : true,
								"bAutoWidth": false,
								"aoColumns": rm_dtl_columns,
								"fnRowCallback": function( nRow, aData, iDisplayIndex ) {
										/* Append the grade to the default row class name */
										console.log(nRow, aData, iDisplayIndex);
										return nRow;
									}
								});
					}
				});
		});
		
		//ADD ITEM
		$('#issue_item').click(function(){
			changeModal({
					'action':'#',
					'model':'rm_dtl',
					'submit_name': 'create-rm_dtl',
					'pr_button':'Return',
					'modal_label': 'Item Return',
					'run': function(){
						
						clear_form('rm_dtl');
					} 
				});
		});
		
		//HEADER SUBMIT HANDLER
		$('#rm-modal-form').submit(function(e){
			//e.preventDefault();
			$('#hidden_data').html('');
			var data = rm_dtl_table.fnGetData();
			var hidden_aggregation = $('#hidden_data');
			$.each(data, function(index, o){
				Object.keys(o).forEach(function(v,i,a){
					hidden_aggregation.append(
						'<input type="hidden" name="rm_dtl['+index+']['+v+']" value="'+o[v]+'"/>');
					});
			});
			//console.log(hidden_aggregation);
		});
				
		//DETAIL SUBMIT HANDLER
		$('#rm_dtl-modal-form').submit(function(e){
			var form = $(this);
			var button_action = form.find('.btn-primary').attr('name');
			e.preventDefault();
			
			var inputs = form.find('input[name]');
			switch(button_action){
				case 'edit-rm_dtl':	
					$.each(inputs, function(i, o) {
						if (current_rm_dtl[$(o).attr('name')]!= 'undefined') {
							current_rm_dtl[$(o).attr('name')] = $(o).val();
						}
					});
					rm_dtl_table.fnUpdate(current_rm_dtl, current_rm_dtl_row);
					break;
				case 'create-rm_dtl':
					current_rm_dtl = {};
					$.each(inputs, function(i, o) {
						current_rm_dtl[$(o).attr('name')] = $(o).val();
					});
					
					current_rm_dtl['rm_dtl_item_no'] = rm_dtl_table.fnGetData().length+1; 
					current_rm_dtl['rm_dtl_item_created'] = (new Date()).toLocaleString();
					console.log('current_rm_dtl', current_rm_dtl);
					rm_dtl_table.fnAddData(current_rm_dtl);
					break;
				default:
					break;
			};
				$('#rm_dtl-modal').modal('hide');
				$('#rm_dtl-modal-form').find('input').removeAttr('disabled');
		});
		
		
		//ITEM POPULATION
		$('[name="rm_dtl_item_stock_no"]').on('keypress', function(e){
			console.log(e.which);
			if(e.which == 13){
				var input = $(this);
				var item_stock_no = input.val();
				if(item_stock_no.length){
					$.post('requisition/bystockno', {stock_no : item_stock_no}, function(data){
						item = (data.data)?data.data:false;
						if(item){
							$('[name="rm_dtl_item_acct_no"]').val(item.item_acct_no);
							$('[name="rm_dtl_item_desc"]').val(item.item_desc);
							$('[name="rm_dtl_item_size"]').val(item.item_size);
							$('[name="rm_dtl_item_unit"]').val(item.item_unit_measure);
						
						}
					});
				}
			}
		});
	
		
	
	})(jQuery);
</script>