<style>
	.supplier .border { padding: 5px; }
	.supplier .border-space{ padding: 5px 5px; }
	#supplier-table th:last-child { width: 5%; }
	
	.dataTables_filter label{
		width:250px;
	}
	[name="supplier-table_length"],[name="supplier-dtl-table_length"]{
		display: inline;
		width: 100px;
		height: 34px;
		padding: 6px 12px;
		font-size: 14px;
		line-height: 1.428571429;
		color: #555555;
		vertical-align: middle;
		background-color: #ffffff;
		background-image: none;
		border: 1px solid #cccccc;
		border-radius: 4px;
	}
</style>
<div class="row">
	<div class="col-md-12">
		<h3>Suppliers <small>Item(s) / Materials supplier</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Supplier
			</li>
		</ol>
		<?php include('_message.phtml'); ?>
	</div>
</div>
<div class="border">
	<div class="border-space col-md-offset-11 col-md-1">
		<button class="btn btn-primary pull-right" data-toggle="modal" data-target="#supplier-modal" 
			data-backdrop="static" data-keyboard="false" id="create-supplier">Add</button>
	</div>
	<hr />
	<div class="row supplier-list border-space">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-hover table-striped table-bordered" id="supplier-table">
					<thead>
						<tr>
							<th>Name</th>
							<th>TIN</th>
							<th>Tax Type</th>
							<th>Address</th>
							<th>Telephone No.</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- Modal -->
<form class="form-horizontal" role="form" action="" method="post" id="supplier-modal-form">
<div class="modal fade" id="supplier-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
      </div>
      <div class="modal-body">
			<input type="hidden" name="supplier_id"/>
		  <div class="form-group ">
		    <label for="input-name" class="col-sm-3 control-label">Name:</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="input-name" placeholder="Enter Name" name="supplier_name" required="required">
		    </div>
		  </div>
		  <div class="form-group ">
		    <label for="input-name" class="col-sm-3 control-label">TIN </label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="input-name" placeholder="Enter TIN" name="supplier_tin" required="required">
		    </div>
		  </div>
		  <div class="form-group ">
		    <label for="input-name" class="col-sm-3 control-label">Tax Type</label>
		    <div class="col-sm-6">
		      <select class="form-control" name="supplier_vat" required="required">
					<option value="">Select</option>
					<option value="VAT">VAT</option>
					<option value="NON-VAT">NON-VAT</option>
					</select>
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-address" class="col-sm-3 control-label">Address:</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="input-address" placeholder="Enter Address" name="supplier_address" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-sm-3 control-label">Tel No:</label>
		    <div class="col-xs-6">
		      <input type="text" class="form-control" id="input-tel" placeholder="Enter Tel No" name="supplier_tel_no">
		    </div>
		  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" name="supplier"><span class="modal-form-action">Save changes</span></button>
      </div>
    </div>
  </div>
</div>
</form>
<?php include __DIR__.'/action.phtml'; ?>
<script type="text/javascript" src="/assets/js/modal_control.js"></script>
<script type="text/javascript">
(function($) {
	$(document).ready(function() {
		var supplier_table = {};
		var action_template = $('#action_tpl').text().trim();
		var supplier_columns = [
			{ "mData": "supplier_name" },
			{ "mData": "supplier_tin" },
			{ "mData": "supplier_vat" },
			{ "mData": "supplier_address" },
			{ "mData": "supplier_tel_no" },
			{
				'mData': function(data){
					var model = new RegExp('//model//','g');
					var model_id = new RegExp('/model_id/','g'); 
					var target_modal = new RegExp('//target-modal//','g'); 
					var action = action_template
						.replace(model, 'supplier')
						.replace(target_modal, 'supplier')
						.replace(model_id, data.supplier_id);
					return action;
				}
			}];
		var supplier_table = $('#supplier-table').dataTable({
			'sPaginationType' : "two_button",
			"iDisplayLength" : 10,
			"sDom" : '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
			'sAjaxSource': '/supplier/',
			'sAjaxDataProp': 'data',
			"bAutoWidth": false,
			"aoColumns": supplier_columns,
			"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
			  oSettings.jqXHR = $.ajax( {
				"dataType": 'json',
				"type": "POST",
				"url": sSource,
				"data": {supplier:'all'},
				"success": fnCallback
			  } );
			}
		})
		
		//CREATE Supplier
		$('#create-supplier').click(function(){
			changeModal({
					'action':'/supplier/add',
					'model':'supplier',
					'submit_name': 'create-supplier',
					'pr_button':'Add',
					'modal_label': 'Add Supplier',
					'run': function(){
						clear_form('supplier');
					}
			});
		});
		
		$(document).on('click','a',function(){
			var action_handle = $(this);
			var row = action_handle.parents('tr:first');
			var  supplier_id;
			//EDIT  Supplier
			if(action_handle.hasClass('edit-supplier')) {
				var row_position = supplier_table.fnGetPosition(row[0]); 
				var row_data = supplier_table.fnGetData(row[0]);
				current_supplier = row_data;
				current_supplier_row = row_position;
				changeModal({
					'action':'/supplier/edit',
					'model':'supplier',
					'submit_name': 'edit-supplier',
					'pr_button':'Save Changes',
					'modal_label': 'Edit Supplier',
					'run': function(){
						populate({
							'data': current_supplier,
							'name':'supplier',
							'map': function(v, o){ return o[v]; }
						}, function(){
							$('#supplier-modal .secondary').show();
						});	
						$('#supplier-modal-form').find('input').removeAttr('disabled');
					}
				});
			}
			//VIEW Supplier
			if(action_handle.hasClass('view-supplier')) {
				var row_position = supplier_table.fnGetPosition(row[0]); 
				var row_data = supplier_table.fnGetData(row[0]);
				current_supplier = row_data;
				current_supplier_row = row_position;
				changeModal({
					'action':'/supplier',
					'model':'supplier',
					'submit_name': 'view-supplier',
					'pr_button':'Back To List',
					'modal_label': 'View Supplier',
					'run': function(){
						populate({
							'data': current_supplier,
							'name':'supplier',
							'map': function(v, o){ return o[v]; }},
							function(){
								$('#supplier-modal .secondary').hide();
								$('#supplier-modal-form').find('input').attr('disabled','disabled');
							}
							);
						
					}
				});
			}
		});
		
	});
})(jQuery);
</script>
