<style>
	.supplier .border {
		padding: 5px;
	}
	.supplier .border-space{ padding: 5px 5px; }
	
	.supplier .pad-it {
		margin-bottom: 20px;
	}
	#addSupplier a { text-decoration: none; }
</style>
<div class="row">
	<div class="col-md-12">
		<h3>Suppliers <small>Item(s) / Materials supplier</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/"><i class="icon-dashboard"></i> Inventory</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i> Supplier
			</li>
		</ol>
	</div>
</div>
<div class="border">
	<div class="border-space col-md-offset-11 col-md-1">
		<button class="btn btn-primary" data-toggle="modal" data-target="#supplier-modal" 
			data-backdrop="static" data-keyboard="false" id="add-supplier">Add</button>
	</div>
	<hr />
	<div class="row supplier-list border-space">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-hover table-striped table-bordered" id="supplier-list">
					<thead>
						<tr>
							<th>Name</th>
							<th>Address</th>
							<th>Telephone No.</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="supplier-modal" tabindex="-1" role="dialog" aria-labelledby="mymodallabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="my-modal-label"><span class="modal-form-state">Action Here</span></h4>
      </div>
      <div class="modal-body">
      	<form class="form-horizontal" role="form" action="" method="post" name="add-supplier" id="supplier-modal-form">
      		<input type="hidden" name="supplier_id"/>
		  <div class="form-group ">
		    <label for="input-name" class="col-sm-2 control-label">Name:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="input-name" placeholder="Enter Name" name="supplier_name" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-address" class="col-sm-2 control-label">Address:</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="input-address" placeholder="Enter Address" name="supplier_address" required="required">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="input-tel" class="col-sm-2 control-label">Tel No. :</label>
		    <div class="col-xs-4">
		      <input type="text" class="form-control" id="input-tel" placeholder="Enter Tel No" name="supplier_tel_no">
		    </div>
		  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" name=""><span class="modal-form-action">Save changes</span></button>
      </div>
      </form>
    </div>
  </div>
</div>
<script type="text/html" id="action_tpl">
	<input type="hidden" name="supplier_serialize" value='//serialize//'/>
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
	    Action <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" role="menu">
	    <li><a href="#" data-toggle="modal" data-target="#supplier-modal" 
	    	data-backdrop="static" data-keyboard="false" class="edit-supplier">Edit</a></li>
	    <li><a href="/supplier/delete/\\supplier_id\\" class="delete-supplier">Delete</a></li>
	    <li><a href="#" data-toggle="modal" data-target="#supplier-modal"
	    	data-backdrop="static" data-keyboard="false"class="view-supplier" >View</a></li>
	  </ul>
	</div>
</script>
<script type="text/javascript">
(function($) {
	
	var tableHandle;
	//tableHandle._fnAjaxUpdate() <-- TO GET FROM SERVER
	//tableHandle.fnDraw()   <-- TO DRAW
	$(document).ready(function() {
		var actionTemplate = $('#action_tpl')
			.text()
			.trim();
			
		tableHandle = $('#supplier-list').dataTable( {
			'sPaginationType': 'two_button',
			'iDisplayLength': 10,
			'sDom': '<"pad-it"<"pull-right"f>l>t<"pull-right"i>p>',
			'sAjaxSource': '/supplier/',
			'sAjaxDataProp': 'data',
			"aoColumns": [
		            { "mData": "supplier_name" },
		            { "mData": "supplier_address" },
		            { "mData": "supplier_tel_no" },
		            {
		            	'mData': function(data){
							var action = actionTemplate
								//.replace('\/\/serialize\/\/',JSON.stringify(data))
								.replace('\\supplier_id\\', data.supplier_id);
		            		return action;
		            		
		            	}
		            }]
		} );
			
		var supplier = {};
		var add = ['/supplier/add','Add','Add Supplier','add-supplier'];
		var edit = ['/supplier/edit','Save Changes','Edit Supplier', 'edit-supplier'];
		var view = ['','Ok','View Supplier', 'view-supplier'];
		
		function changeModal(action) {
			$('#supplier-modal-form').attr('action', action[0]);
			var modal_action = $('#supplier-modal-form')
				.parents('div.modal-content')
				.find('span.modal-form-action');
			modal_action.html(action[1]);
			$('#supplier-modal-form').attr('name', action[3])
				.parents('div.modal-content')
				.find('#my-modal-label').html(action[2]);
		}
		
		$('#add-supplier').on('click',function() {
			changeModal(add);
		});
		
		$(document).on('click', '.edit-supplier', function() {
			console.log('hey');
			changeModal(edit);
			var supplier = JSON.parse($(this)
				.parents('td:first')
				.find('input:hidden')
				.val()
				.trim());
			var form = $('form[name="'+edit[3]+'"]');
			$.each(Object.keys(supplier), function(i, e){
				form.find('input[name="'+e+'"]')
					.val(supplier[e]);
				form.find('textarea[name="'+e+'"]')
					.val(supplier[e]);
			});
		});
		
		$(document).on('click', '.view-supplier', function() {
			changeModal(view);
		});	
	});
})(jQuery);
</script>
