<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/assets/css/uploads/uploadifive.css">

<div class="row-fluid">
	<div class="col-md-12">
		<h3>Item Images Upload <small>Item Snapshots</small></h3>
		<ol class="breadcrumb">
			<li>
				<a href="/">
					<i class="icon-dashboard"></i>
					Inventory
				</a>
			</li>
			<li class="active">
				<i class="icon-file-alt"></i>
				Item
			</li>
		</ol>
		<?php include('_message.phtml'); ?>
	</div>
</div>
<script src="/assets/js/upload/jquery.uploadifive.min.js" type="text/javascript"></script>
<style type="text/css">
body {
	font: 13px Arial, Helvetica, Sans-serif;
}
.uploadifive-button {
	float: left;
	margin-right: 10px;
}
#queue {
	border: 1px solid #E5E5E5;
	height: 177px;
	overflow: auto;
	margin-bottom: 10px;
	margin-top: 20px;
	padding: 0 3px 3px;
	width: 300px;
}
</style>
<form>
	<span>*Image name must be the same as stock number. Example(5000 001.jpg)</span>
	<div id="queue"></div>
	<input id="file_upload" name="file_upload" type="file" multiple="true">
	<a style="position: relative; top: 8px;" href="javascript:$('#file_upload').uploadifive('upload')">Upload Files</a>
</form>

<script type="text/javascript">
	<?php $timestamp = time();?>
	$(function() {
		$('#file_upload').uploadifive({
			'auto'             : false,
			'checkScript'      : '/upload_handler/check',
			'formData'         : {
								   'timestamp' : '<?php echo $timestamp;?>',
								   'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
								 },
			'queueID'          : 'queue',
			'uploadScript'     : '/upload_handler',
			'onUploadComplete' : function(file, data) { console.log(data); }
		});
	});
</script>